//! AutoEQ 耳机校正数据（内嵌）
//!
//! 数据来源：AutoEq 项目 (github.com/jaakkopasanen/AutoEq, MIT 许可)，
//! 测量者 oratory1990。由脚本从 ParametricEQ.txt 生成，勿手改。

// 测量数据中的 Q 值（如 3.14）是真实值，非数学常数近似
#![allow(clippy::approx_constant)]

use super::{HeadphoneProfile, ProfileFilter, ProfileFilterKind};

/// 内嵌耳机档案表
pub(crate) static PROFILES: &[HeadphoneProfile] = &[
    HeadphoneProfile {
        name: "AKG K361",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -2.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 149.0,
                gain_db: -3.3,
                q: 1.47,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4019.0,
                gain_db: 5.9,
                q: 2.87,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 75.0,
                gain_db: 1.3,
                q: 2.02,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 42.0,
                gain_db: -1.4,
                q: 1.64,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.2,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2560.0,
                gain_db: -1.0,
                q: 2.54,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 378.0,
                gain_db: 0.7,
                q: 1.79,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7330.0,
                gain_db: 2.4,
                q: 5.94,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1338.0,
                gain_db: -1.0,
                q: 2.72,
            },
        ],
    },
    HeadphoneProfile {
        name: "AKG K371",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.6,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -2.7,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 182.0,
                gain_db: -2.3,
                q: 1.23,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4038.0,
                gain_db: 5.0,
                q: 3.6,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 67.0,
                gain_db: 3.1,
                q: 1.41,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1066.0,
                gain_db: -0.8,
                q: 2.57,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: 2.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5564.0,
                gain_db: -1.6,
                q: 3.89,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4232.0,
                gain_db: 0.9,
                q: 5.03,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 524.0,
                gain_db: 0.3,
                q: 1.66,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2048.0,
                gain_db: 0.5,
                q: 4.67,
            },
        ],
    },
    HeadphoneProfile {
        name: "AKG K702",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.1,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 7.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 119.0,
                gain_db: -2.7,
                q: 0.23,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9459.0,
                gain_db: 3.2,
                q: 3.19,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 730.0,
                gain_db: 3.2,
                q: 1.22,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2241.0,
                gain_db: -3.5,
                q: 3.8,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.7,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3721.0,
                gain_db: 3.4,
                q: 2.02,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5483.0,
                gain_db: -4.7,
                q: 4.79,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2633.0,
                gain_db: -2.0,
                q: 5.29,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 56.0,
                gain_db: -0.6,
                q: 2.62,
            },
        ],
    },
    HeadphoneProfile {
        name: "AKG K712",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.9,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 143.0,
                gain_db: -3.6,
                q: 0.23,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1217.0,
                gain_db: 5.0,
                q: 1.43,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3049.0,
                gain_db: 4.8,
                q: 3.18,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2178.0,
                gain_db: -3.4,
                q: 3.3,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -0.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5868.0,
                gain_db: -2.6,
                q: 5.87,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 67.0,
                gain_db: -0.6,
                q: 1.75,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 157.0,
                gain_db: 0.9,
                q: 1.87,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 243.0,
                gain_db: -0.5,
                q: 2.27,
            },
        ],
    },
    HeadphoneProfile {
        name: "Apple AirPods Max",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -4.7,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -3.0,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7273.0,
                gain_db: 3.6,
                q: 2.41,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 218.0,
                gain_db: -2.9,
                q: 1.41,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1031.0,
                gain_db: -3.2,
                q: 0.99,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3185.0,
                gain_db: 3.1,
                q: 0.56,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -5.5,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9508.0,
                gain_db: 2.7,
                q: 2.2,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 66.0,
                gain_db: 0.6,
                q: 1.65,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4045.0,
                gain_db: 2.1,
                q: 5.82,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4834.0,
                gain_db: -1.8,
                q: 6.0,
            },
        ],
    },
    HeadphoneProfile {
        name: "Audeze LCD-1",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.1,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.5,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 254.0,
                gain_db: -2.8,
                q: 0.18,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6878.0,
                gain_db: 6.2,
                q: 0.87,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2007.0,
                gain_db: 6.5,
                q: 1.82,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3036.0,
                gain_db: -5.1,
                q: 1.53,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -5.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 76.0,
                gain_db: -1.1,
                q: 2.49,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 42.0,
                gain_db: 0.5,
                q: 1.14,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1026.0,
                gain_db: -1.3,
                q: 3.94,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 720.0,
                gain_db: 0.7,
                q: 1.89,
            },
        ],
    },
    HeadphoneProfile {
        name: "Audio-Technica ATH-M50x",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -3.1,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 0.6,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 156.0,
                gain_db: -5.2,
                q: 0.73,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 326.0,
                gain_db: 5.3,
                q: 1.59,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7077.0,
                gain_db: 2.8,
                q: 2.22,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3483.0,
                gain_db: 2.1,
                q: 5.82,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -4.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 45.0,
                gain_db: -1.1,
                q: 1.9,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 66.0,
                gain_db: 1.4,
                q: 3.59,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 787.0,
                gain_db: -0.5,
                q: 1.79,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1640.0,
                gain_db: 0.9,
                q: 3.41,
            },
        ],
    },
    HeadphoneProfile {
        name: "Beyerdynamic DT 770 Pro",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.1,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -3.0,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6430.0,
                gain_db: -4.2,
                q: 0.97,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3684.0,
                gain_db: 6.8,
                q: 2.88,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 213.0,
                gain_db: 3.5,
                q: 2.46,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 139.0,
                gain_db: -3.9,
                q: 4.92,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -5.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 93.0,
                gain_db: 3.5,
                q: 3.0,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9561.0,
                gain_db: 2.3,
                q: 1.86,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 45.0,
                gain_db: -1.3,
                q: 1.74,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 119.0,
                gain_db: -2.1,
                q: 5.83,
            },
        ],
    },
    HeadphoneProfile {
        name: "Beyerdynamic DT 990 Pro",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.7,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 10.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 541.0,
                gain_db: 3.1,
                q: 0.52,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 64.0,
                gain_db: -7.4,
                q: 0.38,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7731.0,
                gain_db: -4.6,
                q: 1.06,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 640.0,
                gain_db: 0.6,
                q: 2.47,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -9.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7136.0,
                gain_db: 3.1,
                q: 2.08,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5897.0,
                gain_db: -4.8,
                q: 5.3,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4193.0,
                gain_db: 1.1,
                q: 1.51,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9436.0,
                gain_db: 2.7,
                q: 3.53,
            },
        ],
    },
    HeadphoneProfile {
        name: "Beyerdynamic DT 1990 (balanced earpads)",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -4.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 3.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 206.0,
                gain_db: -3.8,
                q: 0.38,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2099.0,
                gain_db: 2.5,
                q: 2.08,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 787.0,
                gain_db: 3.3,
                q: 0.75,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4397.0,
                gain_db: 4.2,
                q: 4.53,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -5.2,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7240.0,
                gain_db: -2.1,
                q: 3.48,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 54.0,
                gain_db: -0.4,
                q: 1.48,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 85.0,
                gain_db: 0.6,
                q: 2.98,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4716.0,
                gain_db: 1.0,
                q: 5.98,
            },
        ],
    },
    HeadphoneProfile {
        name: "Focal Clear",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 7.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8789.0,
                gain_db: 4.5,
                q: 1.48,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1236.0,
                gain_db: -3.8,
                q: 2.26,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 73.0,
                gain_db: -3.6,
                q: 0.36,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4557.0,
                gain_db: 3.8,
                q: 4.14,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.6,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2219.0,
                gain_db: 2.0,
                q: 3.33,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3136.0,
                gain_db: -1.1,
                q: 3.33,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1563.0,
                gain_db: -0.9,
                q: 4.71,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5934.0,
                gain_db: -0.8,
                q: 6.0,
            },
        ],
    },
    HeadphoneProfile {
        name: "HIFIMAN Ananda",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.6,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1755.0,
                gain_db: 5.0,
                q: 1.29,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 116.0,
                gain_db: -2.6,
                q: 0.27,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3131.0,
                gain_db: -3.7,
                q: 2.16,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 945.0,
                gain_db: -2.1,
                q: 3.57,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.5,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 572.0,
                gain_db: -0.4,
                q: 2.88,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5534.0,
                gain_db: 1.9,
                q: 5.98,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4472.0,
                gain_db: -0.7,
                q: 3.39,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 67.0,
                gain_db: -0.5,
                q: 2.78,
            },
        ],
    },
    HeadphoneProfile {
        name: "HIFIMAN Edition XS",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -4.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 5.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 87.0,
                gain_db: -2.8,
                q: 0.33,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1896.0,
                gain_db: 4.0,
                q: 1.92,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2896.0,
                gain_db: -3.7,
                q: 3.11,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1420.0,
                gain_db: 1.3,
                q: 3.89,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -5.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5585.0,
                gain_db: 1.7,
                q: 6.0,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 70.0,
                gain_db: -0.4,
                q: 2.12,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 111.0,
                gain_db: 0.4,
                q: 1.64,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 927.0,
                gain_db: -0.9,
                q: 6.0,
            },
        ],
    },
    HeadphoneProfile {
        name: "HIFIMAN HE400se",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.0,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.7,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1968.0,
                gain_db: 5.1,
                q: 2.37,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 861.0,
                gain_db: -2.3,
                q: 1.86,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 101.0,
                gain_db: -2.4,
                q: 0.32,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1619.0,
                gain_db: 1.1,
                q: 3.53,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -2.6,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 138.0,
                gain_db: 0.7,
                q: 1.98,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 64.0,
                gain_db: -0.7,
                q: 1.95,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 251.0,
                gain_db: -0.4,
                q: 2.33,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 29.0,
                gain_db: 0.5,
                q: 2.63,
            },
        ],
    },
    HeadphoneProfile {
        name: "HIFIMAN Sundara (post-2020 earpads)",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.6,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 8.9,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 56.0,
                gain_db: -4.5,
                q: 0.4,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 971.0,
                gain_db: -1.8,
                q: 1.62,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2115.0,
                gain_db: 2.1,
                q: 2.21,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8270.0,
                gain_db: 1.4,
                q: 0.96,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -3.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 246.0,
                gain_db: -0.6,
                q: 1.21,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 128.0,
                gain_db: 0.7,
                q: 1.44,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 59.0,
                gain_db: -0.6,
                q: 2.26,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 35.0,
                gain_db: 0.2,
                q: 1.56,
            },
        ],
    },
    HeadphoneProfile {
        name: "Meze 99 Classics",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.6,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -2.2,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 232.0,
                gain_db: -20.0,
                q: 0.62,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3754.0,
                gain_db: 11.5,
                q: 1.48,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 320.0,
                gain_db: 15.7,
                q: 0.55,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4636.0,
                gain_db: -10.1,
                q: 1.53,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1026.0,
                gain_db: 3.3,
                q: 3.11,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 633.0,
                gain_db: -1.5,
                q: 0.74,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9590.0,
                gain_db: 2.3,
                q: 3.0,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 379.0,
                gain_db: 2.1,
                q: 3.96,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sennheiser HD 560S",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.6,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 9.0,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8983.0,
                gain_db: 4.4,
                q: 2.63,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 54.0,
                gain_db: -5.4,
                q: 0.48,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1148.0,
                gain_db: -1.5,
                q: 2.38,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 491.0,
                gain_db: 0.6,
                q: 1.23,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -3.9,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7451.0,
                gain_db: 2.0,
                q: 3.91,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4502.0,
                gain_db: -1.7,
                q: 6.0,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1937.0,
                gain_db: 0.9,
                q: 3.93,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5639.0,
                gain_db: -0.9,
                q: 6.0,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sennheiser HD 600",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.3,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.5,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 125.0,
                gain_db: -2.7,
                q: 0.55,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8445.0,
                gain_db: 3.3,
                q: 1.61,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 522.0,
                gain_db: 0.7,
                q: 1.02,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1298.0,
                gain_db: -1.2,
                q: 2.14,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -3.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3158.0,
                gain_db: -1.8,
                q: 3.67,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2166.0,
                gain_db: 0.9,
                q: 3.32,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6639.0,
                gain_db: 2.2,
                q: 5.82,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5433.0,
                gain_db: -1.2,
                q: 5.7,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sennheiser HD 650",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.1,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8800.0,
                gain_db: 5.1,
                q: 1.42,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 118.0,
                gain_db: -3.1,
                q: 0.5,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 37.0,
                gain_db: 0.7,
                q: 3.96,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3169.0,
                gain_db: -1.7,
                q: 3.89,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -2.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1227.0,
                gain_db: -1.2,
                q: 2.53,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2055.0,
                gain_db: 1.2,
                q: 3.23,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 587.0,
                gain_db: 0.4,
                q: 1.19,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5332.0,
                gain_db: -1.1,
                q: 5.75,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sennheiser HD 800 S",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.2,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.6,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 142.0,
                gain_db: -2.3,
                q: 0.3,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1959.0,
                gain_db: 2.5,
                q: 0.88,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5679.0,
                gain_db: -4.4,
                q: 4.36,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 212.0,
                gain_db: -0.5,
                q: 2.36,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -4.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1043.0,
                gain_db: -1.0,
                q: 2.89,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1445.0,
                gain_db: 1.0,
                q: 3.43,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2640.0,
                gain_db: -0.9,
                q: 4.01,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3421.0,
                gain_db: 1.3,
                q: 5.47,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sony MDR-7506",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -5.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 10.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5435.0,
                gain_db: -3.8,
                q: 0.9,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 847.0,
                gain_db: 1.9,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 230.0,
                gain_db: 3.7,
                q: 2.08,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 48.0,
                gain_db: -9.5,
                q: 0.52,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: 3.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7530.0,
                gain_db: -1.4,
                q: 3.26,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2916.0,
                gain_db: -1.9,
                q: 5.57,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3748.0,
                gain_db: 2.6,
                q: 5.91,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4456.0,
                gain_db: -1.6,
                q: 6.0,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sony WH-1000XM4",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.1,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -4.2,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 143.0,
                gain_db: -5.2,
                q: 1.1,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2289.0,
                gain_db: 6.1,
                q: 1.57,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 56.0,
                gain_db: 1.2,
                q: 1.19,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5144.0,
                gain_db: -3.2,
                q: 6.0,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.0,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 407.0,
                gain_db: 1.7,
                q: 3.14,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6715.0,
                gain_db: 3.0,
                q: 5.99,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1007.0,
                gain_db: 1.0,
                q: 3.41,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 576.0,
                gain_db: -1.2,
                q: 3.55,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sony WH-1000XM5",
        form: super::HeadphoneForm::OverEar,
        preamp_db: -6.2,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -3.2,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2448.0,
                gain_db: 6.9,
                q: 2.46,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 173.0,
                gain_db: -5.6,
                q: 0.96,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3028.0,
                gain_db: -5.4,
                q: 2.03,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1327.0,
                gain_db: 3.3,
                q: 0.58,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: 4.9,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6110.0,
                gain_db: -2.3,
                q: 5.81,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 875.0,
                gain_db: -1.2,
                q: 4.07,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1197.0,
                gain_db: 1.0,
                q: 3.28,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 63.0,
                gain_db: 0.4,
                q: 2.13,
            },
        ],
    },
    HeadphoneProfile {
        name: "7Hz Salnotes Zero",
        form: super::HeadphoneForm::InEar,
        preamp_db: -2.5,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -0.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7148.0,
                gain_db: 2.5,
                q: 1.39,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 186.0,
                gain_db: -1.3,
                q: 1.35,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 65.0,
                gain_db: 1.7,
                q: 1.11,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1677.0,
                gain_db: -1.1,
                q: 1.82,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -1.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 857.0,
                gain_db: 0.9,
                q: 1.64,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9824.0,
                gain_db: 0.9,
                q: 1.98,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3316.0,
                gain_db: -0.6,
                q: 2.5,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1261.0,
                gain_db: -0.7,
                q: 3.34,
            },
        ],
    },
    HeadphoneProfile {
        name: "Etymotic ER4SR",
        form: super::HeadphoneForm::InEar,
        preamp_db: -6.0,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.0,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2470.0,
                gain_db: -3.7,
                q: 0.94,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7389.0,
                gain_db: 6.4,
                q: 1.15,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 77.0,
                gain_db: 1.2,
                q: 2.2,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1450.0,
                gain_db: -1.8,
                q: 2.27,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: 2.5,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 269.0,
                gain_db: -0.5,
                q: 1.17,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 745.0,
                gain_db: 0.5,
                q: 2.09,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7552.0,
                gain_db: -0.8,
                q: 4.2,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 9634.0,
                gain_db: -1.0,
                q: 5.99,
            },
        ],
    },
    HeadphoneProfile {
        name: "KZ ZSN Pro X",
        form: super::HeadphoneForm::InEar,
        preamp_db: -3.8,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 0.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 928.0,
                gain_db: 5.3,
                q: 0.66,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 166.0,
                gain_db: -3.4,
                q: 0.67,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2193.0,
                gain_db: -4.4,
                q: 0.61,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3392.0,
                gain_db: 6.1,
                q: 2.82,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -4.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6459.0,
                gain_db: 3.5,
                q: 5.25,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4968.0,
                gain_db: -3.5,
                q: 5.59,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4039.0,
                gain_db: 1.3,
                q: 6.0,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5964.0,
                gain_db: 0.9,
                q: 5.91,
            },
        ],
    },
    HeadphoneProfile {
        name: "Moondrop Aria",
        form: super::HeadphoneForm::InEar,
        preamp_db: -3.4,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -0.2,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 164.0,
                gain_db: -2.6,
                q: 0.92,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6460.0,
                gain_db: 3.5,
                q: 2.43,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 659.0,
                gain_db: 1.4,
                q: 1.59,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3108.0,
                gain_db: 0.5,
                q: 1.51,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -5.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8665.0,
                gain_db: 2.1,
                q: 2.79,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1408.0,
                gain_db: -0.5,
                q: 2.3,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 54.0,
                gain_db: 0.9,
                q: 5.32,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 31.0,
                gain_db: -0.4,
                q: 2.21,
            },
        ],
    },
    HeadphoneProfile {
        name: "Moondrop Chu",
        form: super::HeadphoneForm::InEar,
        preamp_db: -2.2,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 0.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8728.0,
                gain_db: 2.3,
                q: 2.4,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 660.0,
                gain_db: 1.2,
                q: 1.92,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 165.0,
                gain_db: -1.2,
                q: 1.08,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 69.0,
                gain_db: 1.7,
                q: 1.26,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -2.5,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1470.0,
                gain_db: -1.1,
                q: 1.68,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 942.0,
                gain_db: 0.7,
                q: 2.78,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4153.0,
                gain_db: 0.6,
                q: 3.72,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2772.0,
                gain_db: -0.5,
                q: 3.46,
            },
        ],
    },
    HeadphoneProfile {
        name: "Samsung Galaxy Buds2 Pro",
        form: super::HeadphoneForm::InEar,
        preamp_db: -2.3,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -2.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7526.0,
                gain_db: 2.2,
                q: 2.78,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 266.0,
                gain_db: -0.8,
                q: 1.35,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3426.0,
                gain_db: -2.3,
                q: 3.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 64.0,
                gain_db: 2.2,
                q: 1.18,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -3.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 8817.0,
                gain_db: 1.6,
                q: 2.28,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2283.0,
                gain_db: 1.2,
                q: 3.75,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4955.0,
                gain_db: -1.2,
                q: 5.11,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 977.0,
                gain_db: 1.0,
                q: 5.18,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sennheiser IE 600",
        form: super::HeadphoneForm::InEar,
        preamp_db: -5.3,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -2.7,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4374.0,
                gain_db: 5.0,
                q: 1.28,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 196.0,
                gain_db: -1.9,
                q: 1.5,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1727.0,
                gain_db: -2.8,
                q: 1.16,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 798.0,
                gain_db: 1.5,
                q: 1.45,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -7.6,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 72.0,
                gain_db: 1.4,
                q: 1.93,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5857.0,
                gain_db: 3.3,
                q: 5.8,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 143.0,
                gain_db: -0.7,
                q: 3.18,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4796.0,
                gain_db: -0.6,
                q: 4.12,
            },
        ],
    },
    HeadphoneProfile {
        name: "Shure SE215",
        form: super::HeadphoneForm::InEar,
        preamp_db: -5.7,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 0.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 174.0,
                gain_db: -4.6,
                q: 0.68,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 811.0,
                gain_db: 3.1,
                q: 1.42,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3430.0,
                gain_db: 3.8,
                q: 4.37,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6943.0,
                gain_db: 5.4,
                q: 2.76,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: 3.8,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5725.0,
                gain_db: 8.1,
                q: 1.13,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5056.0,
                gain_db: -10.9,
                q: 2.93,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 7269.0,
                gain_db: -6.3,
                q: 3.47,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2278.0,
                gain_db: -2.1,
                q: 2.94,
            },
        ],
    },
    HeadphoneProfile {
        name: "Sony WF-1000XM5",
        form: super::HeadphoneForm::InEar,
        preamp_db: -2.6,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 5.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 68.0,
                gain_db: -4.8,
                q: 0.27,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1377.0,
                gain_db: 2.6,
                q: 0.31,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1806.0,
                gain_db: -3.5,
                q: 1.16,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6875.0,
                gain_db: 1.8,
                q: 3.49,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: 2.3,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3757.0,
                gain_db: 0.3,
                q: 2.56,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 5057.0,
                gain_db: -0.7,
                q: 5.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 449.0,
                gain_db: 0.3,
                q: 4.15,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 677.0,
                gain_db: -0.2,
                q: 2.75,
            },
        ],
    },
    HeadphoneProfile {
        name: "Truthear Hexa",
        form: super::HeadphoneForm::InEar,
        preamp_db: -3.2,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: -0.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4844.0,
                gain_db: 3.4,
                q: 1.81,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 199.0,
                gain_db: -1.9,
                q: 1.54,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 62.0,
                gain_db: 1.6,
                q: 1.05,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 3160.0,
                gain_db: -2.1,
                q: 3.72,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -4.4,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 707.0,
                gain_db: 1.0,
                q: 1.89,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 6318.0,
                gain_db: 1.6,
                q: 5.54,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 349.0,
                gain_db: -0.5,
                q: 2.22,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2113.0,
                gain_db: 0.6,
                q: 3.41,
            },
        ],
    },
    HeadphoneProfile {
        name: "Truthear x Crinacle Zero",
        form: super::HeadphoneForm::InEar,
        preamp_db: -4.3,
        filters: &[
            ProfileFilter {
                kind: ProfileFilterKind::LowShelf,
                freq: 105.0,
                gain_db: 6.7,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 254.0,
                gain_db: 3.6,
                q: 0.38,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 71.0,
                gain_db: -7.3,
                q: 0.42,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 4967.0,
                gain_db: -2.5,
                q: 3.55,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 2574.0,
                gain_db: -1.4,
                q: 1.07,
            },
            ProfileFilter {
                kind: ProfileFilterKind::HighShelf,
                freq: 10000.0,
                gain_db: -2.1,
                q: 0.7,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 352.0,
                gain_db: -0.6,
                q: 2.27,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 658.0,
                gain_db: 0.6,
                q: 2.25,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 207.0,
                gain_db: 0.6,
                q: 3.05,
            },
            ProfileFilter {
                kind: ProfileFilterKind::Peaking,
                freq: 1186.0,
                gain_db: -0.4,
                q: 2.72,
            },
        ],
    },
];
