// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_ringbuf_impl`, `fill_buffer_stereo_impl`, `fill_buffer_stereo_inner`, `probe_log`, `set_hw_sample_rate_impl`, `set_playing_impl`, `update_spectrum`

/// 由 Swift 通过 extern "C" 调用，设置硬件采样率
Future<void> setHwSampleRate({required int rate}) =>
    RustLib.instance.api.crateApiAudioOutputSetHwSampleRate(rate: rate);

Future<int> getHwSampleRate() =>
    RustLib.instance.api.crateApiAudioOutputGetHwSampleRate();

/// 读取当前频谱（16 频段，0~1）
Future<Float32List> getSpectrum() =>
    RustLib.instance.api.crateApiAudioOutputGetSpectrum();

/// 读取 underrun 计数
Future<BigInt> getUnderrunCount() =>
    RustLib.instance.api.crateApiAudioOutputGetUnderrunCount();
