// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 解析 .cue 文件，返回分轨表
Future<CueSheetResult> parseCueFile({required String path}) =>
    RustLib.instance.api.crateApiCueParseCueFile(path: path);

/// CUE 文件条目（对应一个物理音频文件）
class CueFileResult {
  final String path;
  final List<CueTrackResult> tracks;

  const CueFileResult({required this.path, required this.tracks});

  @override
  int get hashCode => path.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueFileResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          tracks == other.tracks;
}

/// CUE 分轨解析结果
class CueSheetResult {
  final String? title;
  final String? performer;
  final List<CueFileResult> files;

  const CueSheetResult({this.title, this.performer, required this.files});

  @override
  int get hashCode => title.hashCode ^ performer.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueSheetResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          performer == other.performer &&
          files == other.files;
}

/// CUE 音轨
class CueTrackResult {
  final String num;
  final String? title;
  final String? performer;
  final double startSecs;
  final double pregapSecs;

  const CueTrackResult({
    required this.num,
    this.title,
    this.performer,
    required this.startSecs,
    required this.pregapSecs,
  });

  @override
  int get hashCode =>
      num.hashCode ^
      title.hashCode ^
      performer.hashCode ^
      startSecs.hashCode ^
      pregapSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueTrackResult &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          title == other.title &&
          performer == other.performer &&
          startSecs == other.startSecs &&
          pregapSecs == other.pregapSecs;
}
