// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SourceFormatDto`

/// 列举所有输出设备
Future<List<DeviceInfoDto>> enumerateDevices() =>
    RustLib.instance.api.crateApiDeviceEnumerateDevices();

/// 输出决策：设备 + 源格式 → 最优输出配置
Future<OutputDecisionDto?> decideOutput({
  required String deviceId,
  required int sourceSr,
  required int sourceBits,
  required int sourceCh,
  required bool sourceIsDsd,
  required bool preferExclusive,
}) => RustLib.instance.api.crateApiDeviceDecideOutput(
  deviceId: deviceId,
  sourceSr: sourceSr,
  sourceBits: sourceBits,
  sourceCh: sourceCh,
  sourceIsDsd: sourceIsDsd,
  preferExclusive: preferExclusive,
);

/// 启动设备热插拔监测
Future<void> deviceMonitorStart() =>
    RustLib.instance.api.crateApiDeviceDeviceMonitorStart();

/// 停止设备热插拔监测
Future<void> deviceMonitorStop() =>
    RustLib.instance.api.crateApiDeviceDeviceMonitorStop();

/// 轮询设备事件（Dart 侧定期调用，返回后事件即丢弃）
Future<List<String>> deviceMonitorPollEvents() =>
    RustLib.instance.api.crateApiDeviceDeviceMonitorPollEvents();

/// 输出设备信息（给 Dart 展示设备列表用）
class DeviceInfoDto {
  final String id;
  final String name;
  final bool isDefault;
  final bool isUsb;

  const DeviceInfoDto({
    required this.id,
    required this.name,
    required this.isDefault,
    required this.isUsb,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ isDefault.hashCode ^ isUsb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault &&
          isUsb == other.isUsb;
}

/// 输出决策结果
class OutputDecisionDto {
  final String deviceId;
  final int sampleRate;
  final int bitDepth;
  final bool exclusive;
  final bool needResample;
  final String reason;

  const OutputDecisionDto({
    required this.deviceId,
    required this.sampleRate,
    required this.bitDepth,
    required this.exclusive,
    required this.needResample,
    required this.reason,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      sampleRate.hashCode ^
      bitDepth.hashCode ^
      exclusive.hashCode ^
      needResample.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputDecisionDto &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          sampleRate == other.sampleRate &&
          bitDepth == other.bitDepth &&
          exclusive == other.exclusive &&
          needResample == other.needResample &&
          reason == other.reason;
}
