// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EqPreset`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// AutoEQ 耳机校正档案目录（oratory1990 实测，型号名供设置页展示，
/// 选中后经 `engine_set_auto_eq` 应用）
Future<List<String>> autoEqCatalog() =>
    RustLib.instance.api.crateApiDspAutoEqCatalog();
