// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine_probe`, `engine_start_stream`, `push_event`, `with_engine`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `engine_read_samples`

/// 初始化引擎，使用 HW_SAMPLE_RATE（由 Swift 设 set_hw_sample_rate 传入）
Future<void> engineInit() => RustLib.instance.api.crateApiEngineEngineInit();

/// 完整参数初始化引擎
Future<void> engineInitEx({
  required int sr,
  required int channels,
  required int bufferMs,
  required int crossfadeMs,
  required bool bitPerfect,
  required bool autoSampleRate,
  required bool exclusiveMode,
  String? outputDevice,
}) => RustLib.instance.api.crateApiEngineEngineInitEx(
  sr: sr,
  channels: channels,
  bufferMs: bufferMs,
  crossfadeMs: crossfadeMs,
  bitPerfect: bitPerfect,
  autoSampleRate: autoSampleRate,
  exclusiveMode: exclusiveMode,
  outputDevice: outputDevice,
);

/// 从引擎 ringbuf 读取最多 `frames` 帧的交错立体声 PCM（Android 流式播放用）。
///
/// 返回长度可能小于 `frames*2`（ringbuf 数据不足），调用方应自行处理欠载。
Future<Float32List> engineReadSamplesFrames({required int frames}) =>
    RustLib.instance.api.crateApiEngineEngineReadSamplesFrames(frames: frames);

Future<void> engineDeinit() =>
    RustLib.instance.api.crateApiEngineEngineDeinit();

Future<String?> enginePollEvents() =>
    RustLib.instance.api.crateApiEngineEnginePollEvents();

/// 检查是否有新的事件发生并返回事件类型
Future<String?> engineTakeEvent() =>
    RustLib.instance.api.crateApiEngineEngineTakeEvent();

/// 主动推送引擎错误事件（非引擎线程/流式喂流 task 用）。
///
/// 背景：SMB 边下边播的喂流 task 在首块成功后若中途失败（连接断/读超时/
/// 网络波动），core 侧解码线程只看到 channel 断开 → EOF → 播完缓冲后发
/// `stopped`，Dart 无法区分「正常播完」与「断流」，会当曲终切歌。此处
/// 让喂流 task 失败时主动注入 error 事件，Dart `_tick` 的 error 分支
/// （_playingFromStream 时回退全量下载）即可接管。
Future<void> engineNotifyStreamError({required String message}) => RustLib
    .instance
    .api
    .crateApiEngineEngineNotifyStreamError(message: message);

Future<void> enginePlay({required String path}) =>
    RustLib.instance.api.crateApiEngineEnginePlay(path: path);

Future<void> enginePlayQueue({required List<String> paths}) =>
    RustLib.instance.api.crateApiEngineEnginePlayQueue(paths: paths);

/// 从指定下标起播队列（0-based；CUE 分轨场景：传入 .cue 路径由 core 展开
/// 为虚拟分轨后从 [start_index] 起播）。
Future<void> enginePlayQueueAt({
  required List<String> paths,
  required int startIndex,
}) => RustLib.instance.api.crateApiEngineEnginePlayQueueAt(
  paths: paths,
  startIndex: startIndex,
);

Future<void> enginePause() => RustLib.instance.api.crateApiEngineEnginePause();

Future<void> engineResume() =>
    RustLib.instance.api.crateApiEngineEngineResume();

Future<void> engineStop() => RustLib.instance.api.crateApiEngineEngineStop();

Future<void> engineSeek({required double posSecs}) =>
    RustLib.instance.api.crateApiEngineEngineSeek(posSecs: posSecs);

Future<void> engineNext() => RustLib.instance.api.crateApiEngineEngineNext();

Future<void> enginePrev() => RustLib.instance.api.crateApiEngineEnginePrev();

Future<void> engineSetPeqBand({
  required int index,
  required double freq,
  required double gainDb,
  required double q,
}) => RustLib.instance.api.crateApiEngineEngineSetPeqBand(
  index: index,
  freq: freq,
  gainDb: gainDb,
  q: q,
);

Future<void> engineApplyPreset({required String presetName}) => RustLib
    .instance
    .api
    .crateApiEngineEngineApplyPreset(presetName: presetName);

Future<void> engineSetVolume({required double vol}) =>
    RustLib.instance.api.crateApiEngineEngineSetVolume(vol: vol);

Future<void> engineSetStereoWidener({
  required bool enabled,
  required double width,
}) => RustLib.instance.api.crateApiEngineEngineSetStereoWidener(
  enabled: enabled,
  width: width,
);

Future<void> engineSetSpeed({required double speed}) =>
    RustLib.instance.api.crateApiEngineEngineSetSpeed(speed: speed);

/// 设置引擎输出采样率（重建输出流，bit-perfect 协调用）。
///
/// - iOS：Swift 先把 `AVAudioSession` 设到目标速率并读回实际速率，Dart 再调用
///   本方法使引擎输出速率与设备一致
/// - Android：无会话协商，Dart 直接以文件速率调用；Oboe 内部先试
///   Exclusive（设备允许即真 bit-perfect），失败回退 Shared
/// 命令走 FIFO 通道，在同一首播放之前发送即可保证先于 play 生效。
/// 若速率 == 文件速率则不重采样（bit-perfect）。
Future<void> engineSetOutputSampleRate({required int rate}) =>
    RustLib.instance.api.crateApiEngineEngineSetOutputSampleRate(rate: rate);

Future<void> engineSetCrossfeed({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineEngineSetCrossfeed(enabled: enabled);

/// 启用/禁用真峰值限幅
Future<void> engineSetLimiter({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineEngineSetLimiter(enabled: enabled);

/// 启用/禁用抖动（含噪声整形）
Future<void> engineSetDither({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineEngineSetDither(enabled: enabled);

Future<void> engineSetPlayMode({required int mode}) =>
    RustLib.instance.api.crateApiEngineEngineSetPlayMode(mode: mode);

Future<void> engineLoadIr({required String path}) =>
    RustLib.instance.api.crateApiEngineEngineLoadIr(path: path);

Future<void> engineClearIr() =>
    RustLib.instance.api.crateApiEngineEngineClearIr();

Future<void> engineSetReplaygainGain({required double gainDb}) =>
    RustLib.instance.api.crateApiEngineEngineSetReplaygainGain(gainDb: gainDb);

/// 设置 ReplayGain 真峰值上限（防过载；None 清除）。
/// 与 [`engine_set_replaygain_gain`] 配套，切歌时按曲目标签逐首下发。
Future<void> engineSetReplaygainPeak({double? peak}) =>
    RustLib.instance.api.crateApiEngineEngineSetReplaygainPeak(peak: peak);

/// 启用/禁用抖动噪声整形（配合 dither 使用，默认关）
Future<void> engineSetNoiseShaping({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineEngineSetNoiseShaping(enabled: enabled);

/// 应用/清除 AutoEQ 耳机校正档案。
/// 型号名取自 `auto_eq_catalog()`；传 None 清除（档案 preamp 自动经
/// ReplayGain 通道叠加防削峰）。
Future<void> engineSetAutoEq({String? model}) =>
    RustLib.instance.api.crateApiEngineEngineSetAutoEq(model: model);

/// 音频会话中断开始（如来电）：引擎暂停。
/// iOS 由 Swift 经 C FFI（`wavelink_session_interruption_began`）直接调用，
/// 同时暴露给 Dart 以便未来 Android 音频焦点场景复用。
Future<void> engineSessionInterruptionBegan() =>
    RustLib.instance.api.crateApiEngineEngineSessionInterruptionBegan();

/// 音频会话中断结束：引擎恢复播放（调用方需自行确认中断前在播）
Future<void> engineSessionInterruptionEnded() =>
    RustLib.instance.api.crateApiEngineEngineSessionInterruptionEnded();

Future<double> enginePositionSecs() =>
    RustLib.instance.api.crateApiEngineEnginePositionSecs();

Future<double> engineDurationSecs() =>
    RustLib.instance.api.crateApiEngineEngineDurationSecs();

Future<bool> engineIsPlaying() =>
    RustLib.instance.api.crateApiEngineEngineIsPlaying();

/// 实际输出共享模式：0=未知/不适用，1=Exclusive，2=Shared（Android Oboe）。
/// 反映「请求 Exclusive 但静默降级为 Shared」的真实结果，指示器据此显示。
Future<int> engineOutputMode() =>
    RustLib.instance.api.crateApiEngineEngineOutputMode();

Future<String> engineCurrentPath() =>
    RustLib.instance.api.crateApiEngineEngineCurrentPath();

Future<String> engineLastError() =>
    RustLib.instance.api.crateApiEngineEngineLastError();

Future<LevelsDto> engineLevels() =>
    RustLib.instance.api.crateApiEngineEngineLevels();

Future<BigInt> engineUnderrunCount() =>
    RustLib.instance.api.crateApiEngineEngineUnderrunCount();

Future<int> engineQueueLen() =>
    RustLib.instance.api.crateApiEngineEngineQueueLen();

Future<String> engineQueuePathAt({required int index}) =>
    RustLib.instance.api.crateApiEngineEngineQueuePathAt(index: index);

Future<void> engineRemoveFromQueue({required int index}) =>
    RustLib.instance.api.crateApiEngineEngineRemoveFromQueue(index: index);

class LevelsDto {
  final double rms;
  final double peak;
  final bool clip;

  const LevelsDto({required this.rms, required this.peak, required this.clip});

  static Future<LevelsDto> default_() =>
      RustLib.instance.api.crateApiEngineLevelsDtoDefault();

  @override
  int get hashCode => rms.hashCode ^ peak.hashCode ^ clip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LevelsDto &&
          runtimeType == other.runtimeType &&
          rms == other.rms &&
          peak == other.peak &&
          clip == other.clip;
}
