// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_cover_lofty`, `mp3_tag_summary`

/// 从音频文件读取 ReplayGain 标签
Future<ReplayGainResult> readReplaygain({required String path}) =>
    RustLib.instance.api.crateApiMetadataReadReplaygain(path: path);

/// 读取音频文件封面图（JPEG/PNG 原始字节），用 lofty 提取
Future<Uint8List> getCoverBytes({required String path}) =>
    RustLib.instance.api.crateApiMetadataGetCoverBytes(path: path);

/// 读取音频文件元数据（标题/艺术家/专辑/封面/时长），同时提取封面字节
/// 避免 Dart 层再调 getCoverBytes 二次解析文件
Future<MetadataResult> readMetadata({required String path}) =>
    RustLib.instance.api.crateApiMetadataReadMetadata(path: path);

/// 音频文件元数据
class MetadataResult {
  final String? title;
  final String? artist;
  final String? album;
  final double durationSecs;
  final bool hasCover;
  final Uint8List coverBytes;

  /// 内嵌歌词（LRC 文本：ID3 USLT / Vorbis LYRICS / MP4 ©lyr）
  final String? lyrics;

  const MetadataResult({
    this.title,
    this.artist,
    this.album,
    required this.durationSecs,
    required this.hasCover,
    required this.coverBytes,
    this.lyrics,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSecs.hashCode ^
      hasCover.hashCode ^
      coverBytes.hashCode ^
      lyrics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSecs == other.durationSecs &&
          hasCover == other.hasCover &&
          coverBytes == other.coverBytes &&
          lyrics == other.lyrics;
}

/// ReplayGain 响度归一化增益值
class ReplayGainResult {
  /// 音轨增益 (dB)，如 -5.23
  final double? trackGainDb;

  /// 专辑增益 (dB)，如 -7.14
  final double? albumGainDb;

  /// 音轨真峰值
  final double? trackPeak;

  /// 专辑真峰值
  final double? albumPeak;

  const ReplayGainResult({
    this.trackGainDb,
    this.albumGainDb,
    this.trackPeak,
    this.albumPeak,
  });

  @override
  int get hashCode =>
      trackGainDb.hashCode ^
      albumGainDb.hashCode ^
      trackPeak.hashCode ^
      albumPeak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplayGainResult &&
          runtimeType == other.runtimeType &&
          trackGainDb == other.trackGainDb &&
          albumGainDb == other.albumGainDb &&
          trackPeak == other.trackPeak &&
          albumPeak == other.albumPeak;
}
