// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err_str`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SmbSession`

/// 连接 SMB 服务器（host 为裸 IP/域名，内部拼 :port）
Future<void> smbConnect({
  required String host,
  required int port,
  required String username,
  required String password,
  required String domain,
}) => RustLib.instance.api.crateApiSmbSmbConnect(
  host: host,
  port: port,
  username: username,
  password: password,
  domain: domain,
);

/// 断开 SMB 连接
Future<void> smbDisconnect() => RustLib.instance.api.crateApiSmbSmbDisconnect();

/// 列出服务器所有共享
Future<List<SmbShareInfo>> smbListShares() =>
    RustLib.instance.api.crateApiSmbSmbListShares();

/// 挂载指定共享（后续 list/read 均相对该共享根目录）
Future<void> smbConnectShare({required String shareName}) =>
    RustLib.instance.api.crateApiSmbSmbConnectShare(shareName: shareName);

/// 列出目录内容；path 空串表示共享根目录，子路径如 "Music/Album"
Future<List<SmbDirEntry>> smbListDirectory({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbListDirectory(path: path);

/// 读取远端文件完整内容（相对共享根目录的路径）
Future<Uint8List> smbReadFile({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbReadFile(path: path);

/// 远端文件大小（扫描时判断是否有变化，避免重复下载）
Future<BigInt> smbFileSize({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbFileSize(path: path);

/// 目录条目（list_directory 用）
class SmbDirEntry {
  final String name;
  final BigInt size;
  final bool isDir;

  const SmbDirEntry({
    required this.name,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbDirEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          isDir == other.isDir;
}

/// 共享信息（list_shares 用）
class SmbShareInfo {
  final String name;
  final String comment;

  const SmbShareInfo({required this.name, required this.comment});

  @override
  int get hashCode => name.hashCode ^ comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbShareInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          comment == other.comment;
}
