// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_basic_auth`, `build_digest_auth`, `err_str`, `feed_webdav_to_core`, `md5_hex`, `parse_www_authenticate`, `random_hex`, `webdav_get`

/// 启动 WebDAV 边下边播：后台 task 从远端分块拉字节喂入 core 解码
/// （首帧即出声），并行写 `.part` 缓存读完 rename（下次播放秒起）。
/// 认证支持 Basic/Digest。返回 Ok 表示流已启动且**首块已喂入 core**；
/// 失败（连接不可用/流被关）返回 Err，Dart 回退全量下载。
Future<void> enginePlayWebdavStream({
  required String url,
  required String username,
  required String password,
  String? formatHint,
  String? cacheFinalPath,
}) => RustLib.instance.api.crateApiWebdavEnginePlayWebdavStream(
  url: url,
  username: username,
  password: password,
  formatHint: formatHint,
  cacheFinalPath: cacheFinalPath,
);
