// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_cover_lofty`

/// 读取音频文件内嵌封面图（原始字节）。无封面返回 Err。
Future<Uint8List> getCoverBytes({required String path}) =>
    RustLib.instance.api.crateApiCoverGetCoverBytes(path: path);
