// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_cue_text`

/// 解析 .cue 文件字节，返回分轨表。
///
/// [data]：cue 文件原始字节（UTF-8 / GBK 均可）；
/// [base_dir]：cue 所在目录，FILE 声明的相对路径以此为基准转绝对。
Future<CueSheetResult> parseCueBytes({
  required List<int> data,
  required String baseDir,
}) =>
    RustLib.instance.api.crateApiCueParseCueBytes(data: data, baseDir: baseDir);

/// CUE 文件条目（对应一个物理音频文件）
class CueFileResult {
  /// 绝对路径（相对声明已按 base_dir 解析）
  final String path;
  final List<CueTrackResult> tracks;

  const CueFileResult({required this.path, required this.tracks});

  @override
  int get hashCode => path.hashCode ^ tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueFileResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          tracks == other.tracks;
}

/// CUE 分轨解析结果
class CueSheetResult {
  final String? title;
  final String? performer;
  final List<CueFileResult> files;

  const CueSheetResult({this.title, this.performer, required this.files});

  @override
  int get hashCode => title.hashCode ^ performer.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueSheetResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          performer == other.performer &&
          files == other.files;
}

/// CUE 音轨
class CueTrackResult {
  final String num;
  final String? title;
  final String? performer;

  /// INDEX 01 在音频文件中的起始时间（秒）
  final double startSecs;

  /// PREGAP 时长（秒），虚拟静音，不存在于音频文件中
  final double pregapSecs;

  const CueTrackResult({
    required this.num,
    this.title,
    this.performer,
    required this.startSecs,
    required this.pregapSecs,
  });

  @override
  int get hashCode =>
      num.hashCode ^
      title.hashCode ^
      performer.hashCode ^
      startSecs.hashCode ^
      pregapSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueTrackResult &&
          runtimeType == other.runtimeType &&
          num == other.num &&
          title == other.title &&
          performer == other.performer &&
          startSecs == other.startSecs &&
          pregapSecs == other.pregapSecs;
}
