// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `duration_of`, `read_duration_from_memory`

/// NAS 文件真实时长（秒）。读文件头经 lofty 内存探测；网络读失败或 lofty
/// 探不到（如 OGG 需尾部页）返回 None，由 Dart 侧回退 estimateDuration。
Future<double?> getNasDuration({
  required String path,
  required BigInt headLimit,
}) => RustLib.instance.api.crateApiDurationGetNasDuration(
  path: path,
  headLimit: headLimit,
);

/// WebDAV 文件真实时长（秒）。读文件头（Range 请求）经 lofty 内存探测；
/// 网络读失败或 lofty 探不到返回 None，由 Dart 侧回退 estimateDuration。
Future<double?> getWebdavDuration({
  required String url,
  required String username,
  required String password,
  required BigInt headLimit,
}) => RustLib.instance.api.crateApiDurationGetWebdavDuration(
  url: url,
  username: username,
  password: password,
  headLimit: headLimit,
);
