// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine_start_stream`, `notify_stream_error`, `push_event`

/// 初始化引擎。成功返回 null；失败返回错误信息字符串。
///
/// `output_device` 为 null 表示系统默认设备。幂等：已初始化时直接返回成功。
Future<String?> wavelinkInit({
  required int sampleRate,
  required int channels,
  required int bufferMs,
  required bool bitPerfect,
  required bool exclusiveMode,
  String? outputDevice,
}) => RustLib.instance.api.crateApiEngineWavelinkInit(
  sampleRate: sampleRate,
  channels: channels,
  bufferMs: bufferMs,
  bitPerfect: bitPerfect,
  exclusiveMode: exclusiveMode,
  outputDevice: outputDevice,
);

/// 释放引擎。与 `wavelink_init` 配对，可重新 init（ENGINE 可重置）。
Future<void> wavelinkDeinit() =>
    RustLib.instance.api.crateApiEngineWavelinkDeinit();

/// 播放单个文件（异步）。
Future<void> wavelinkPlay({required String path}) =>
    RustLib.instance.api.crateApiEngineWavelinkPlay(path: path);

/// 以 JSON 数组（["/a","/b"]）设置播放队列并从第一首播放。
Future<void> wavelinkPlayQueueJson({required String json}) =>
    RustLib.instance.api.crateApiEngineWavelinkPlayQueueJson(json: json);

/// 以 JSON 数组设置播放队列并从 `start_index`（0-based）开始播放（CUE 分轨场景）。
Future<void> wavelinkPlayQueueAtJson({
  required String json,
  required int startIndex,
}) => RustLib.instance.api.crateApiEngineWavelinkPlayQueueAtJson(
  json: json,
  startIndex: startIndex,
);

Future<void> wavelinkPause() =>
    RustLib.instance.api.crateApiEngineWavelinkPause();

Future<void> wavelinkResume() =>
    RustLib.instance.api.crateApiEngineWavelinkResume();

Future<void> wavelinkStop() =>
    RustLib.instance.api.crateApiEngineWavelinkStop();

Future<void> wavelinkNext() =>
    RustLib.instance.api.crateApiEngineWavelinkNext();

Future<void> wavelinkPrev() =>
    RustLib.instance.api.crateApiEngineWavelinkPrev();

/// 跳转到指定位置（秒）
Future<void> wavelinkSeek({required double posSecs}) =>
    RustLib.instance.api.crateApiEngineWavelinkSeek(posSecs: posSecs);

/// 设置音量（0.0 ~ 2.0）
Future<void> wavelinkSetVolume({required double vol}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetVolume(vol: vol);

/// 设置播放模式：0 顺序 / 1 单曲循环 / 2 列表循环 / 3 随机
Future<void> wavelinkSetPlayMode({required int mode}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetPlayMode(mode: mode);

/// 设置输出设备（null = 系统默认），下次播放生效
Future<void> wavelinkSetOutputDevice({String? name}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetOutputDevice(name: name);

Future<double> wavelinkPositionSecs() =>
    RustLib.instance.api.crateApiEngineWavelinkPositionSecs();

Future<double> wavelinkDurationSecs() =>
    RustLib.instance.api.crateApiEngineWavelinkDurationSecs();

Future<bool> wavelinkIsPlaying() =>
    RustLib.instance.api.crateApiEngineWavelinkIsPlaying();

Future<BigInt> wavelinkUnderrunCount() =>
    RustLib.instance.api.crateApiEngineWavelinkUnderrunCount();

Future<String> wavelinkCurrentPath() =>
    RustLib.instance.api.crateApiEngineWavelinkCurrentPath();

Future<String> wavelinkLastError() =>
    RustLib.instance.api.crateApiEngineWavelinkLastError();

/// 抽干事件 channel 入队，再返回一个事件 JSON（需释放）；无事件返回 null。
///
/// Dart 侧应以 ~20-50ms 间隔高频调用，避免事件堆积。
Future<String?> wavelinkPollEvent() =>
    RustLib.instance.api.crateApiEngineWavelinkPollEvent();

/// 枚举可用输出设备，返回 JSON 字符串（需释放）：["设备名1","设备名2"]
Future<List<String>> wavelinkEnumerateDevices() =>
    RustLib.instance.api.crateApiEngineWavelinkEnumerateDevices();

/// 获取当前实际输出采样率（Hz）
Future<int> wavelinkGetOutputSampleRate() =>
    RustLib.instance.api.crateApiEngineWavelinkGetOutputSampleRate();

/// 设置输出采样率（下次播放生效）
Future<void> wavelinkSetOutputSampleRate({required int rate}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetOutputSampleRate(rate: rate);

/// 设置参数均衡器某频段（index 从 0 起）
Future<void> wavelinkSetPeqBand({
  required int index,
  required double freq,
  required double gainDb,
  required double q,
}) => RustLib.instance.api.crateApiEngineWavelinkSetPeqBand(
  index: index,
  freq: freq,
  gainDb: gainDb,
  q: q,
);

/// 应用内置 EQ 预设（flat/rock/pop/dance/classical/soft/full_bass/full_treble/techno/vocals）
Future<void> wavelinkApplyPreset({required String presetName}) => RustLib
    .instance
    .api
    .crateApiEngineWavelinkApplyPreset(presetName: presetName);

/// 设置立体声展宽（width: 0.0 ~ 1.0）
Future<void> wavelinkSetStereoWidener({
  required bool enabled,
  required double width,
}) => RustLib.instance.api.crateApiEngineWavelinkSetStereoWidener(
  enabled: enabled,
  width: width,
);

/// 设置播放速度（0.25 ~ 4.0），1.0 = 正常
Future<void> wavelinkSetSpeed({required double speed}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetSpeed(speed: speed);

/// 设置跨馈（耳机化立体声）
Future<void> wavelinkSetCrossfeed({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetCrossfeed(enabled: enabled);

/// 启用/禁用真峰值限幅
Future<void> wavelinkSetLimiter({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetLimiter(enabled: enabled);

/// 启用/禁用抖动（含噪声整形）
Future<void> wavelinkSetDither({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetDither(enabled: enabled);

/// 启用/禁用 ATH 噪声整形
Future<void> wavelinkSetNoiseShaping({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiEngineWavelinkSetNoiseShaping(enabled: enabled);

/// 设置 ReplayGain 增益（dB），作为 Pre-amp 在 EQ 前应用
Future<void> wavelinkSetReplaygainGain({required double gainDb}) => RustLib
    .instance
    .api
    .crateApiEngineWavelinkSetReplaygainGain(gainDb: gainDb);

/// 设置 ReplayGain 真峰值上限（防过载；None = 不限制）
Future<void> wavelinkSetReplaygainPeak({double? peak}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetReplaygainPeak(peak: peak);

/// 应用/清除 AutoEQ 耳机校正档案（型号名；null/空 = 清除恢复平坦）
Future<void> wavelinkSetAutoEq({String? model}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetAutoEq(model: model);

/// 加载脉冲响应文件（房间校正 FIR 卷积），下次播放生效
Future<void> wavelinkLoadIr({required String path}) =>
    RustLib.instance.api.crateApiEngineWavelinkLoadIr(path: path);

/// 清除脉冲响应（恢复平坦响应）
Future<void> wavelinkClearIr() =>
    RustLib.instance.api.crateApiEngineWavelinkClearIr();
