// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine_start_stream`, `notify_stream_error`, `push_event`

/// 初始化引擎。成功返回 null；失败返回错误信息字符串。
///
/// `output_device` 为 null 表示系统默认设备。幂等：已初始化时直接返回成功。
Future<String?> wavelinkInit({
  required int sampleRate,
  required int channels,
  required int bufferMs,
  required bool bitPerfect,
  required bool exclusiveMode,
  String? outputDevice,
}) => RustLib.instance.api.crateApiEngineWavelinkInit(
  sampleRate: sampleRate,
  channels: channels,
  bufferMs: bufferMs,
  bitPerfect: bitPerfect,
  exclusiveMode: exclusiveMode,
  outputDevice: outputDevice,
);

/// 释放引擎。与 `wavelink_init` 配对，可重新 init（ENGINE 可重置）。
Future<void> wavelinkDeinit() =>
    RustLib.instance.api.crateApiEngineWavelinkDeinit();

/// 播放单个文件（异步）。
Future<void> wavelinkPlay({required String path}) =>
    RustLib.instance.api.crateApiEngineWavelinkPlay(path: path);

/// 以 JSON 数组（["/a","/b"]）设置播放队列并从第一首播放。
Future<void> wavelinkPlayQueueJson({required String json}) =>
    RustLib.instance.api.crateApiEngineWavelinkPlayQueueJson(json: json);

/// 以 JSON 数组设置播放队列并从 `start_index`（0-based）开始播放（CUE 分轨场景）。
Future<void> wavelinkPlayQueueAtJson({
  required String json,
  required int startIndex,
}) => RustLib.instance.api.crateApiEngineWavelinkPlayQueueAtJson(
  json: json,
  startIndex: startIndex,
);

Future<void> wavelinkPause() =>
    RustLib.instance.api.crateApiEngineWavelinkPause();

Future<void> wavelinkResume() =>
    RustLib.instance.api.crateApiEngineWavelinkResume();

Future<void> wavelinkStop() =>
    RustLib.instance.api.crateApiEngineWavelinkStop();

Future<void> wavelinkNext() =>
    RustLib.instance.api.crateApiEngineWavelinkNext();

Future<void> wavelinkPrev() =>
    RustLib.instance.api.crateApiEngineWavelinkPrev();

/// 跳转到指定位置（秒）
Future<void> wavelinkSeek({required double posSecs}) =>
    RustLib.instance.api.crateApiEngineWavelinkSeek(posSecs: posSecs);

/// 设置音量（0.0 ~ 2.0）
Future<void> wavelinkSetVolume({required double vol}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetVolume(vol: vol);

/// 设置播放模式：0 顺序 / 1 单曲循环 / 2 列表循环 / 3 随机
Future<void> wavelinkSetPlayMode({required int mode}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetPlayMode(mode: mode);

/// 设置输出设备（null = 系统默认），下次播放生效
Future<void> wavelinkSetOutputDevice({String? name}) =>
    RustLib.instance.api.crateApiEngineWavelinkSetOutputDevice(name: name);

Future<double> wavelinkPositionSecs() =>
    RustLib.instance.api.crateApiEngineWavelinkPositionSecs();

Future<double> wavelinkDurationSecs() =>
    RustLib.instance.api.crateApiEngineWavelinkDurationSecs();

Future<bool> wavelinkIsPlaying() =>
    RustLib.instance.api.crateApiEngineWavelinkIsPlaying();

Future<BigInt> wavelinkUnderrunCount() =>
    RustLib.instance.api.crateApiEngineWavelinkUnderrunCount();

Future<String> wavelinkCurrentPath() =>
    RustLib.instance.api.crateApiEngineWavelinkCurrentPath();

Future<String> wavelinkLastError() =>
    RustLib.instance.api.crateApiEngineWavelinkLastError();

/// 抽干事件 channel 入队，再返回一个事件 JSON（需释放）；无事件返回 null。
///
/// Dart 侧应以 ~20-50ms 间隔高频调用，避免事件堆积。
Future<String?> wavelinkPollEvent() =>
    RustLib.instance.api.crateApiEngineWavelinkPollEvent();

/// 枚举可用输出设备，返回 JSON 字符串（需释放）：["设备名1","设备名2"]
Future<List<String>> wavelinkEnumerateDevices() =>
    RustLib.instance.api.crateApiEngineWavelinkEnumerateDevices();
