// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_core`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// 默认校正配置（与 core 对齐）
Future<CorrectionConfig> defaultCorrectionConfig() =>
    RustLib.instance.api.crateApiRoomDefaultCorrectionConfig();

/// 解析 REW 频响导出文本（不生成 IR，供校验/预览）。
/// 返回有效测量点（Hz/dB），解析失败返回错误字符串。
Future<List<FreqPoint>> parseRewText({required String text}) =>
    RustLib.instance.api.crateApiRoomParseRewText(text: text);

/// 生成房间校正 IR：REW 测量文本 → 校正 FIR 系数。
///
/// `sample_rate` 建议传引擎输出采样率（默认 44100）；生成的 WAV 在加载时
/// 若与管线采样率不一致会被卷积器自动重采样。
Future<RoomCorrectionResult> generateRoomCorrection({
  required String rewTxt,
  required CorrectionConfig config,
  required int sampleRate,
}) => RustLib.instance.api.crateApiRoomGenerateRoomCorrection(
  rewTxt: rewTxt,
  config: config,
  sampleRate: sampleRate,
);

/// 保存 IR 为 32-bit float WAV（单声道），供 `engine_load_ir` 加载。
Future<void> saveIrWav({
  required List<double> ir,
  required int sampleRate,
  required String path,
}) => RustLib.instance.api.crateApiRoomSaveIrWav(
  ir: ir,
  sampleRate: sampleRate,
  path: path,
);

/// 校正配置（FRB 兼容结构；target 取 "flat" / "harman_tilt"）
class CorrectionConfig {
  /// 目标曲线："flat"（平坦）/ "harman_tilt"（房间缓降，1kHz 以下 +1.3dB/oct）
  final String target;

  /// FIR 长度（tap 数，偶数，64~65536，越大低频分辨率越高）
  final int taps;

  /// 最大削减（dB，限制对峰/正偏差的衰减幅度，防过削）
  final double maxCutDb;

  /// null 补偿上限（dB，限制对负偏差的补偿幅度，防硬补无效）
  final double nullLimitDb;

  /// 校正频率范围下限（Hz）
  final double freqMin;

  /// 校正频率范围上限（Hz）
  final double freqMax;

  /// 心理声学频段权重（300Hz 以下全量，向高频平滑递减）
  final bool psychoWeighting;

  /// 曲线平滑分辨率（octave，典型 1/6）
  final double smoothingOctave;

  /// IR 峰值归一化 headroom（dB，预留防削峰余量）
  final double headroomDb;

  const CorrectionConfig({
    required this.target,
    required this.taps,
    required this.maxCutDb,
    required this.nullLimitDb,
    required this.freqMin,
    required this.freqMax,
    required this.psychoWeighting,
    required this.smoothingOctave,
    required this.headroomDb,
  });

  @override
  int get hashCode =>
      target.hashCode ^
      taps.hashCode ^
      maxCutDb.hashCode ^
      nullLimitDb.hashCode ^
      freqMin.hashCode ^
      freqMax.hashCode ^
      psychoWeighting.hashCode ^
      smoothingOctave.hashCode ^
      headroomDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CorrectionConfig &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          taps == other.taps &&
          maxCutDb == other.maxCutDb &&
          nullLimitDb == other.nullLimitDb &&
          freqMin == other.freqMin &&
          freqMax == other.freqMax &&
          psychoWeighting == other.psychoWeighting &&
          smoothingOctave == other.smoothingOctave &&
          headroomDb == other.headroomDb;
}

/// 单点频响数据（Hz / dB），测量曲线预览用
class FreqPoint {
  /// 频率（Hz）
  final double freq;

  /// 电平（dB）
  final double levelDb;

  const FreqPoint({required this.freq, required this.levelDb});

  @override
  int get hashCode => freq.hashCode ^ levelDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FreqPoint &&
          runtimeType == other.runtimeType &&
          freq == other.freq &&
          levelDb == other.levelDb;
}

/// 房间校正生成结果
class RoomCorrectionResult {
  /// 生成的 IR 系数（单声道，目标采样率）
  final Float32List ir;

  /// IR 采样率
  final int sampleRate;

  /// 整体归一化应用的增益（dB；负值 = 整体衰减，UI 应提示补偿音量）
  final double appliedGainDb;

  /// 有效测量点数
  final BigInt points;

  /// 解析出的测量曲线（UI 预览用）
  final List<FreqPoint> measured;

  const RoomCorrectionResult({
    required this.ir,
    required this.sampleRate,
    required this.appliedGainDb,
    required this.points,
    required this.measured,
  });

  @override
  int get hashCode =>
      ir.hashCode ^
      sampleRate.hashCode ^
      appliedGainDb.hashCode ^
      points.hashCode ^
      measured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoomCorrectionResult &&
          runtimeType == other.runtimeType &&
          ir == other.ir &&
          sampleRate == other.sampleRate &&
          appliedGainDb == other.appliedGainDb &&
          points == other.points &&
          measured == other.measured;
}
