// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `acquire_pool_permit`, `cleanup_stale_part_stream`, `connect_share_with_timeout`, `connect_with_timeout`, `ensure_pooled_tree`, `err_str`, `feed_stream_to_core`, `random_hex`, `to_config`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectParams`, `SmbSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

/// 连接 SMB 服务器（host 为裸 IP/域名，内部拼 :port）#[frb]
Future<void> smbConnect({
  required String host,
  required int port,
  required String username,
  required String password,
  required String domain,
}) => RustLib.instance.api.crateApiSmbSmbConnect(
  host: host,
  port: port,
  username: username,
  password: password,
  domain: domain,
);

/// 前台保活：对主会话 + 读取池每条连接发一次 fs_info，返回是否全部健康。
///
/// smb2 crate 的 keepalive 只探测「有请求在途但线路静默」的连接，
/// 完全空闲的连接从不被探测；而多数 NAS 会话空闲超时（常见几分钟）
/// 会在前台闲置时悄悄回收连接，下次真实 IO 踩到死连接只能
/// 白等 crate 硬编码的 30s RESPONSE_TIMEOUT 才判死。故由 Dart 侧
/// 每隔一段时间主动调本函数，让每条连接保持活跃、NAS 不回收。
/// fs_info 是只读轻量请求，语义与 reviver 可重放的读操作一致。
///
/// 返回 false：任一连接探活失败（含 5s 超时）——Dart 侧据此 force
/// 重建会话。早期版本用 let _ = 吞错导致探活永远"成功"，死连接
/// 无人清理、真实 IO 反复白等 30s（封面批量提取连环超时的根因）。#[frb]
Future<bool> smbKeepalive() => RustLib.instance.api.crateApiSmbSmbKeepalive();

/// 断开 SMB 连接（含读取池）#[frb]
Future<void> smbDisconnect() => RustLib.instance.api.crateApiSmbSmbDisconnect();

/// 列出服务器所有共享#[frb]
Future<List<SmbShareInfo>> smbListShares() =>
    RustLib.instance.api.crateApiSmbSmbListShares();

/// 挂载指定共享（后续 list/read 均相对该共享根目录）
///
/// 同时在读取池的每条连接上挂载，保证并行下载可用。#[frb]
Future<void> smbConnectShare({required String shareName}) =>
    RustLib.instance.api.crateApiSmbSmbConnectShare(shareName: shareName);

/// 列出目录内容；path 空串表示共享根目录，子路径如 "Music/Album"
///
/// 过滤 "."/".." 条目：smb2 crate 会返回它们，
/// 递归扫描时若不剔除会无限进入 "." 导致路径爆炸。
/// 优先从读取池借独立连接，使多个目录可并行列出（避免主会话串行排队）；
/// 池空时回退主会话。#[frb]
Future<List<SmbDirEntry>> smbListDirectory({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbListDirectory(path: path);

/// 读取远端文件完整内容（相对共享根目录的路径）
///
/// 用 read_file_pipelined 而非 read_file：后者单次读取上限 65536 字节，
/// 大于该值的文件（几乎所有音频）会报错。
/// 优先从读取池借独立连接（并行下载），池空时回退主会话。#[frb]
Future<Uint8List> smbReadFile({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbReadFile(path: path);

/// 流式读取远端文件（相对共享根目录的路径），分块经 FRB sink 推给 Dart。
///
/// 会话在流存活期间独占（不回池）：FileReader 与池会话共享同一条
/// 连接，若提前归还，后续任务会在同一链路上发并发请求（连接多路
/// 复用），部分 NAS 固件无法处理，READ 返回空数据/Protocol error，
/// 表现为下载得到 0 字节。独占后每路流一条独立链路，互不干扰；
/// 并发上限仍由 POOL_SEM 控制。每块 512KB 推送一次，Dart 端逐块
/// 追加写入，避免整文件跨 FFI 一次性拷贝。#[frb]
Stream<Uint8List> smbReadFileStream({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbReadFileStream(path: path);

Future<Uint8List> smbReadTail({required String path, required BigInt maxLen}) =>
    RustLib.instance.api.crateApiSmbSmbReadTail(path: path, maxLen: maxLen);

/// 读远端文件头部（最多 [max_len] 字节）：封面提取/格式探测用，避免整文件下载。
/// 会话在读完前独占（不回池）：与 smb_read_file_stream 同理，提前归还
/// 会让后续任务在同一连接上发并发请求，部分 NAS 无法处理。#[frb]
Future<Uint8List> smbReadHead({required String path, required BigInt maxLen}) =>
    RustLib.instance.api.crateApiSmbSmbReadHead(path: path, maxLen: maxLen);

/// 读远端文件指定区间 `[offset, offset+max_len)`（相对共享根目录的路径）。
/// 并发分片下载原语：Dart 侧把整曲切成多片并行调用，各片独立连接读取，
/// 打满 NAS 带宽（单连接顺序读受单会话吞吐限制）。
/// 会话在读完前独占（不回池）：与 smb_read_head 同理，避免同连接并发请求。
/// 返回实际读到的字节（可能少于 max_len，取决于文件大小/读池状态）。#[frb]
Future<Uint8List> smbReadFileRange({
  required String path,
  required BigInt offset,
  required BigInt maxLen,
}) => RustLib.instance.api.crateApiSmbSmbReadFileRange(
  path: path,
  offset: offset,
  maxLen: maxLen,
);

/// 远端文件大小（下载完整性校验用）#[frb]
Future<BigInt> smbFileSize({required String path}) =>
    RustLib.instance.api.crateApiSmbSmbFileSize(path: path);

/// 边下边播：SMB 远端文件 → core 流式解码（首帧即出声）＋并行写本地缓存。
///
/// 流程：启动 core `play_stream` 拿到 StreamHandle → spawn 后台喂流 task，
/// 独占一条池连接从远端读 512KB 分块，每块 `handle.write` 喂给 core 解码
/// （同时追加写 `.smb_cache/*.part`），读尽后 `signal_eof` 并 rename 成正式
/// 缓存（下次播放秒起）；若流被关闭（切歌/stop，`write` 返回 0）立即退出
/// 并清理残留 `.part`，避免半截缓存被误命中。
///
/// [format_hint]：远端文件扩展名（"mp3"/"flac"…），core 据此选择解码器，
/// 传 None 则纯靠 symphonia 自动探测。返回 Ok 即表示流已启动且**首块已喂入
/// core**（probe 拿到数据，ready 大概率达成）。失败（连接不可用/流被关）
/// 返回 Err，Dart 回退全量下载；不再 fire-and-forget 导致失败静默。
/// [content_length]：远端文件真实字节数（扫描期已知），作为流总长度传给
/// core，使 symphonia 结合比特率算出**真实时长**（FLAC 用 STREAMINFO 精确，
/// CBR 用 字节数/比特率），进度条因此准确；None 则退化为 Dart 侧粗估。#[frb]
Future<void> enginePlaySmbStream({
  required String smbPath,
  String? formatHint,
  String? cacheFinalPath,
  BigInt? contentLength,
  double? seekSecs,
}) => RustLib.instance.api.crateApiSmbEnginePlaySmbStream(
  smbPath: smbPath,
  formatHint: formatHint,
  cacheFinalPath: cacheFinalPath,
  contentLength: contentLength,
  seekSecs: seekSecs,
);

/// 目录条目（list_directory 用）
class SmbDirEntry {
  final String name;
  final BigInt size;
  final bool isDir;

  const SmbDirEntry({
    required this.name,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbDirEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          isDir == other.isDir;
}

/// 共享信息（list_shares 用）
class SmbShareInfo {
  final String name;
  final String comment;

  const SmbShareInfo({required this.name, required this.comment});

  @override
  int get hashCode => name.hashCode ^ comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbShareInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          comment == other.comment;
}
