// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine.dart';
import 'api/smb.dart';
import 'api/webdav.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0-beta.5';

  @override
  int get rustContentHash => -573905593;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wavelink_desktop',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSmbEnginePlaySmbStream({
    required String smbPath,
    String? formatHint,
    String? cacheFinalPath,
    BigInt? contentLength,
  });

  Future<void> crateApiWebdavEnginePlayWebdavStream({
    required String url,
    required String username,
    required String password,
    String? formatHint,
    String? cacheFinalPath,
    BigInt? contentLength,
  });

  Future<Uint8List> crateApiWebdavEngineReadWebdavRange({
    required String url,
    required String username,
    required String password,
    required BigInt maxLen,
    required bool suffix,
  });

  Future<Uint8List> crateApiWebdavEngineWebdavDownloadRange({
    required String url,
    required String username,
    required String password,
    required BigInt offset,
    required BigInt maxLen,
  });

  Future<BigInt> crateApiWebdavEngineWebdavFileSize({
    required String url,
    required String username,
    required String password,
  });

  Future<void> crateApiSmbSmbConnect({
    required String host,
    required int port,
    required String username,
    required String password,
    required String domain,
  });

  Future<void> crateApiSmbSmbConnectShare({required String shareName});

  Future<void> crateApiSmbSmbDisconnect();

  Future<BigInt> crateApiSmbSmbFileSize({required String path});

  Future<bool> crateApiSmbSmbKeepalive();

  Future<List<SmbDirEntry>> crateApiSmbSmbListDirectory({required String path});

  Future<List<SmbShareInfo>> crateApiSmbSmbListShares();

  Future<Uint8List> crateApiSmbSmbReadFile({required String path});

  Future<Uint8List> crateApiSmbSmbReadFileRange({
    required String path,
    required BigInt offset,
    required BigInt maxLen,
  });

  Stream<Uint8List> crateApiSmbSmbReadFileStream({required String path});

  Future<Uint8List> crateApiSmbSmbReadHead({
    required String path,
    required BigInt maxLen,
  });

  Future<Uint8List> crateApiSmbSmbReadTail({
    required String path,
    required BigInt maxLen,
  });

  Future<String> crateApiEngineWavelinkCurrentPath();

  Future<void> crateApiEngineWavelinkDeinit();

  Future<double> crateApiEngineWavelinkDurationSecs();

  Future<List<String>> crateApiEngineWavelinkEnumerateDevices();

  Future<String?> crateApiEngineWavelinkInit({
    required int sampleRate,
    required int channels,
    required int bufferMs,
    required bool bitPerfect,
    required bool exclusiveMode,
    String? outputDevice,
  });

  Future<bool> crateApiEngineWavelinkIsPlaying();

  Future<String> crateApiEngineWavelinkLastError();

  Future<void> crateApiEngineWavelinkNext();

  Future<void> crateApiEngineWavelinkPause();

  Future<void> crateApiEngineWavelinkPlay({required String path});

  Future<void> crateApiEngineWavelinkPlayQueueAtJson({
    required String json,
    required int startIndex,
  });

  Future<void> crateApiEngineWavelinkPlayQueueJson({required String json});

  Future<String?> crateApiEngineWavelinkPollEvent();

  Future<double> crateApiEngineWavelinkPositionSecs();

  Future<void> crateApiEngineWavelinkPrev();

  Future<void> crateApiEngineWavelinkResume();

  Future<void> crateApiEngineWavelinkSeek({required double posSecs});

  Future<void> crateApiEngineWavelinkSetOutputDevice({String? name});

  Future<void> crateApiEngineWavelinkSetPlayMode({required int mode});

  Future<void> crateApiEngineWavelinkSetVolume({required double vol});

  Future<void> crateApiEngineWavelinkStop();

  Future<BigInt> crateApiEngineWavelinkUnderrunCount();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSmbEnginePlaySmbStream({
    required String smbPath,
    String? formatHint,
    String? cacheFinalPath,
    BigInt? contentLength,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(smbPath, serializer);
          sse_encode_opt_String(formatHint, serializer);
          sse_encode_opt_String(cacheFinalPath, serializer);
          sse_encode_opt_box_autoadd_u_64(contentLength, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbEnginePlaySmbStreamConstMeta,
        argValues: [smbPath, formatHint, cacheFinalPath, contentLength],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbEnginePlaySmbStreamConstMeta =>
      const TaskConstMeta(
        debugName: "engine_play_smb_stream",
        argNames: ["smbPath", "formatHint", "cacheFinalPath", "contentLength"],
      );

  @override
  Future<void> crateApiWebdavEnginePlayWebdavStream({
    required String url,
    required String username,
    required String password,
    String? formatHint,
    String? cacheFinalPath,
    BigInt? contentLength,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_opt_String(formatHint, serializer);
          sse_encode_opt_String(cacheFinalPath, serializer);
          sse_encode_opt_box_autoadd_u_64(contentLength, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebdavEnginePlayWebdavStreamConstMeta,
        argValues: [
          url,
          username,
          password,
          formatHint,
          cacheFinalPath,
          contentLength,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebdavEnginePlayWebdavStreamConstMeta =>
      const TaskConstMeta(
        debugName: "engine_play_webdav_stream",
        argNames: [
          "url",
          "username",
          "password",
          "formatHint",
          "cacheFinalPath",
          "contentLength",
        ],
      );

  @override
  Future<Uint8List> crateApiWebdavEngineReadWebdavRange({
    required String url,
    required String username,
    required String password,
    required BigInt maxLen,
    required bool suffix,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_u_64(maxLen, serializer);
          sse_encode_bool(suffix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebdavEngineReadWebdavRangeConstMeta,
        argValues: [url, username, password, maxLen, suffix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebdavEngineReadWebdavRangeConstMeta =>
      const TaskConstMeta(
        debugName: "engine_read_webdav_range",
        argNames: ["url", "username", "password", "maxLen", "suffix"],
      );

  @override
  Future<Uint8List> crateApiWebdavEngineWebdavDownloadRange({
    required String url,
    required String username,
    required String password,
    required BigInt offset,
    required BigInt maxLen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_u_64(maxLen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebdavEngineWebdavDownloadRangeConstMeta,
        argValues: [url, username, password, offset, maxLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebdavEngineWebdavDownloadRangeConstMeta =>
      const TaskConstMeta(
        debugName: "engine_webdav_download_range",
        argNames: ["url", "username", "password", "offset", "maxLen"],
      );

  @override
  Future<BigInt> crateApiWebdavEngineWebdavFileSize({
    required String url,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWebdavEngineWebdavFileSizeConstMeta,
        argValues: [url, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWebdavEngineWebdavFileSizeConstMeta =>
      const TaskConstMeta(
        debugName: "engine_webdav_file_size",
        argNames: ["url", "username", "password"],
      );

  @override
  Future<void> crateApiSmbSmbConnect({
    required String host,
    required int port,
    required String username,
    required String password,
    required String domain,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(domain, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbConnectConstMeta,
        argValues: [host, port, username, password, domain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbConnectConstMeta => const TaskConstMeta(
    debugName: "smb_connect",
    argNames: ["host", "port", "username", "password", "domain"],
  );

  @override
  Future<void> crateApiSmbSmbConnectShare({required String shareName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(shareName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbConnectShareConstMeta,
        argValues: [shareName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbConnectShareConstMeta => const TaskConstMeta(
    debugName: "smb_connect_share",
    argNames: ["shareName"],
  );

  @override
  Future<void> crateApiSmbSmbDisconnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmbSmbDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbDisconnectConstMeta =>
      const TaskConstMeta(debugName: "smb_disconnect", argNames: []);

  @override
  Future<BigInt> crateApiSmbSmbFileSize({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbFileSizeConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbFileSizeConstMeta =>
      const TaskConstMeta(debugName: "smb_file_size", argNames: ["path"]);

  @override
  Future<bool> crateApiSmbSmbKeepalive() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSmbSmbKeepaliveConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbKeepaliveConstMeta =>
      const TaskConstMeta(debugName: "smb_keepalive", argNames: []);

  @override
  Future<List<SmbDirEntry>> crateApiSmbSmbListDirectory({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_smb_dir_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbListDirectoryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbListDirectoryConstMeta =>
      const TaskConstMeta(debugName: "smb_list_directory", argNames: ["path"]);

  @override
  Future<List<SmbShareInfo>> crateApiSmbSmbListShares() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_smb_share_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbListSharesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbListSharesConstMeta =>
      const TaskConstMeta(debugName: "smb_list_shares", argNames: []);

  @override
  Future<Uint8List> crateApiSmbSmbReadFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbReadFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbReadFileConstMeta =>
      const TaskConstMeta(debugName: "smb_read_file", argNames: ["path"]);

  @override
  Future<Uint8List> crateApiSmbSmbReadFileRange({
    required String path,
    required BigInt offset,
    required BigInt maxLen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_u_64(maxLen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbReadFileRangeConstMeta,
        argValues: [path, offset, maxLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbReadFileRangeConstMeta =>
      const TaskConstMeta(
        debugName: "smb_read_file_range",
        argNames: ["path", "offset", "maxLen"],
      );

  @override
  Stream<Uint8List> crateApiSmbSmbReadFileStream({required String path}) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(path, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSmbSmbReadFileStreamConstMeta,
          argValues: [path, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSmbSmbReadFileStreamConstMeta =>
      const TaskConstMeta(
        debugName: "smb_read_file_stream",
        argNames: ["path", "sink"],
      );

  @override
  Future<Uint8List> crateApiSmbSmbReadHead({
    required String path,
    required BigInt maxLen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_64(maxLen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbReadHeadConstMeta,
        argValues: [path, maxLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbReadHeadConstMeta => const TaskConstMeta(
    debugName: "smb_read_head",
    argNames: ["path", "maxLen"],
  );

  @override
  Future<Uint8List> crateApiSmbSmbReadTail({
    required String path,
    required BigInt maxLen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_u_64(maxLen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSmbSmbReadTailConstMeta,
        argValues: [path, maxLen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSmbSmbReadTailConstMeta => const TaskConstMeta(
    debugName: "smb_read_tail",
    argNames: ["path", "maxLen"],
  );

  @override
  Future<String> crateApiEngineWavelinkCurrentPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkCurrentPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkCurrentPathConstMeta =>
      const TaskConstMeta(debugName: "wavelink_current_path", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkDeinit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkDeinitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkDeinitConstMeta =>
      const TaskConstMeta(debugName: "wavelink_deinit", argNames: []);

  @override
  Future<double> crateApiEngineWavelinkDurationSecs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkDurationSecsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkDurationSecsConstMeta =>
      const TaskConstMeta(debugName: "wavelink_duration_secs", argNames: []);

  @override
  Future<List<String>> crateApiEngineWavelinkEnumerateDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkEnumerateDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkEnumerateDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "wavelink_enumerate_devices",
        argNames: [],
      );

  @override
  Future<String?> crateApiEngineWavelinkInit({
    required int sampleRate,
    required int channels,
    required int bufferMs,
    required bool bitPerfect,
    required bool exclusiveMode,
    String? outputDevice,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(sampleRate, serializer);
          sse_encode_u_32(channels, serializer);
          sse_encode_u_32(bufferMs, serializer);
          sse_encode_bool(bitPerfect, serializer);
          sse_encode_bool(exclusiveMode, serializer);
          sse_encode_opt_String(outputDevice, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkInitConstMeta,
        argValues: [
          sampleRate,
          channels,
          bufferMs,
          bitPerfect,
          exclusiveMode,
          outputDevice,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkInitConstMeta => const TaskConstMeta(
    debugName: "wavelink_init",
    argNames: [
      "sampleRate",
      "channels",
      "bufferMs",
      "bitPerfect",
      "exclusiveMode",
      "outputDevice",
    ],
  );

  @override
  Future<bool> crateApiEngineWavelinkIsPlaying() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkIsPlayingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkIsPlayingConstMeta =>
      const TaskConstMeta(debugName: "wavelink_is_playing", argNames: []);

  @override
  Future<String> crateApiEngineWavelinkLastError() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkLastErrorConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkLastErrorConstMeta =>
      const TaskConstMeta(debugName: "wavelink_last_error", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkNext() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkNextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkNextConstMeta =>
      const TaskConstMeta(debugName: "wavelink_next", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkPause() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPauseConstMeta =>
      const TaskConstMeta(debugName: "wavelink_pause", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkPlay({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPlayConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPlayConstMeta =>
      const TaskConstMeta(debugName: "wavelink_play", argNames: ["path"]);

  @override
  Future<void> crateApiEngineWavelinkPlayQueueAtJson({
    required String json,
    required int startIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          sse_encode_u_32(startIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPlayQueueAtJsonConstMeta,
        argValues: [json, startIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPlayQueueAtJsonConstMeta =>
      const TaskConstMeta(
        debugName: "wavelink_play_queue_at_json",
        argNames: ["json", "startIndex"],
      );

  @override
  Future<void> crateApiEngineWavelinkPlayQueueJson({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPlayQueueJsonConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPlayQueueJsonConstMeta =>
      const TaskConstMeta(
        debugName: "wavelink_play_queue_json",
        argNames: ["json"],
      );

  @override
  Future<String?> crateApiEngineWavelinkPollEvent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPollEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPollEventConstMeta =>
      const TaskConstMeta(debugName: "wavelink_poll_event", argNames: []);

  @override
  Future<double> crateApiEngineWavelinkPositionSecs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPositionSecsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPositionSecsConstMeta =>
      const TaskConstMeta(debugName: "wavelink_position_secs", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkPrev() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkPrevConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkPrevConstMeta =>
      const TaskConstMeta(debugName: "wavelink_prev", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkResume() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkResumeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkResumeConstMeta =>
      const TaskConstMeta(debugName: "wavelink_resume", argNames: []);

  @override
  Future<void> crateApiEngineWavelinkSeek({required double posSecs}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(posSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkSeekConstMeta,
        argValues: [posSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkSeekConstMeta =>
      const TaskConstMeta(debugName: "wavelink_seek", argNames: ["posSecs"]);

  @override
  Future<void> crateApiEngineWavelinkSetOutputDevice({String? name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkSetOutputDeviceConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkSetOutputDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "wavelink_set_output_device",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiEngineWavelinkSetPlayMode({required int mode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkSetPlayModeConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkSetPlayModeConstMeta =>
      const TaskConstMeta(
        debugName: "wavelink_set_play_mode",
        argNames: ["mode"],
      );

  @override
  Future<void> crateApiEngineWavelinkSetVolume({required double vol}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(vol, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkSetVolumeConstMeta,
        argValues: [vol],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkSetVolumeConstMeta =>
      const TaskConstMeta(debugName: "wavelink_set_volume", argNames: ["vol"]);

  @override
  Future<void> crateApiEngineWavelinkStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkStopConstMeta =>
      const TaskConstMeta(debugName: "wavelink_stop", argNames: []);

  @override
  Future<BigInt> crateApiEngineWavelinkUnderrunCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEngineWavelinkUnderrunCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEngineWavelinkUnderrunCountConstMeta =>
      const TaskConstMeta(debugName: "wavelink_underrun_count", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SmbDirEntry> dco_decode_list_smb_dir_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_smb_dir_entry).toList();
  }

  @protected
  List<SmbShareInfo> dco_decode_list_smb_share_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_smb_share_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  SmbDirEntry dco_decode_smb_dir_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SmbDirEntry(
      name: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
      isDir: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SmbShareInfo dco_decode_smb_share_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SmbShareInfo(
      name: dco_decode_String(arr[0]),
      comment: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SmbDirEntry> sse_decode_list_smb_dir_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SmbDirEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_smb_dir_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<SmbShareInfo> sse_decode_list_smb_share_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SmbShareInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_smb_share_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SmbDirEntry sse_decode_smb_dir_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    return SmbDirEntry(name: var_name, size: var_size, isDir: var_isDir);
  }

  @protected
  SmbShareInfo sse_decode_smb_share_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_comment = sse_decode_String(deserializer);
    return SmbShareInfo(name: var_name, comment: var_comment);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_smb_dir_entry(
    List<SmbDirEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_smb_dir_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_smb_share_info(
    List<SmbShareInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_smb_share_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_smb_dir_entry(SmbDirEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_bool(self.isDir, serializer);
  }

  @protected
  void sse_encode_smb_share_info(SmbShareInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.comment, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
