// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/analyze.dart';
import 'api/cover.dart';
import 'api/cue.dart';
import 'api/duration.dart';
import 'api/engine.dart';
import 'api/metadata.dart';
import 'api/room.dart';
import 'api/smb.dart';
import 'api/webdav.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnalyzeResult dco_decode_analyze_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CorrectionConfig dco_decode_box_autoadd_correction_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  HeadMetadataDto dco_decode_box_autoadd_head_metadata_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CorrectionConfig dco_decode_correction_config(dynamic raw);

  @protected
  CueFileResult dco_decode_cue_file_result(dynamic raw);

  @protected
  CueSheetResult dco_decode_cue_sheet_result(dynamic raw);

  @protected
  CueTrackResult dco_decode_cue_track_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FreqPoint dco_decode_freq_point(dynamic raw);

  @protected
  HeadMetadataDto dco_decode_head_metadata_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CueFileResult> dco_decode_list_cue_file_result(dynamic raw);

  @protected
  List<CueTrackResult> dco_decode_list_cue_track_result(dynamic raw);

  @protected
  List<FreqPoint> dco_decode_list_freq_point(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SmbDirEntry> dco_decode_list_smb_dir_entry(dynamic raw);

  @protected
  List<SmbShareInfo> dco_decode_list_smb_share_info(dynamic raw);

  @protected
  MetadataResult dco_decode_metadata_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  HeadMetadataDto? dco_decode_opt_box_autoadd_head_metadata_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  RoomCorrectionResult dco_decode_room_correction_result(dynamic raw);

  @protected
  SmbDirEntry dco_decode_smb_dir_entry(dynamic raw);

  @protected
  SmbShareInfo dco_decode_smb_share_info(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnalyzeResult sse_decode_analyze_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CorrectionConfig sse_decode_box_autoadd_correction_config(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HeadMetadataDto sse_decode_box_autoadd_head_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CorrectionConfig sse_decode_correction_config(SseDeserializer deserializer);

  @protected
  CueFileResult sse_decode_cue_file_result(SseDeserializer deserializer);

  @protected
  CueSheetResult sse_decode_cue_sheet_result(SseDeserializer deserializer);

  @protected
  CueTrackResult sse_decode_cue_track_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FreqPoint sse_decode_freq_point(SseDeserializer deserializer);

  @protected
  HeadMetadataDto sse_decode_head_metadata_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CueFileResult> sse_decode_list_cue_file_result(
    SseDeserializer deserializer,
  );

  @protected
  List<CueTrackResult> sse_decode_list_cue_track_result(
    SseDeserializer deserializer,
  );

  @protected
  List<FreqPoint> sse_decode_list_freq_point(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SmbDirEntry> sse_decode_list_smb_dir_entry(SseDeserializer deserializer);

  @protected
  List<SmbShareInfo> sse_decode_list_smb_share_info(
    SseDeserializer deserializer,
  );

  @protected
  MetadataResult sse_decode_metadata_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  HeadMetadataDto? sse_decode_opt_box_autoadd_head_metadata_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  RoomCorrectionResult sse_decode_room_correction_result(
    SseDeserializer deserializer,
  );

  @protected
  SmbDirEntry sse_decode_smb_dir_entry(SseDeserializer deserializer);

  @protected
  SmbShareInfo sse_decode_smb_share_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_analyze_result(AnalyzeResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_correction_config(
    CorrectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_head_metadata_dto(
    HeadMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_correction_config(
    CorrectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cue_file_result(CueFileResult self, SseSerializer serializer);

  @protected
  void sse_encode_cue_sheet_result(
    CueSheetResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cue_track_result(
    CueTrackResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_freq_point(FreqPoint self, SseSerializer serializer);

  @protected
  void sse_encode_head_metadata_dto(
    HeadMetadataDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cue_file_result(
    List<CueFileResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cue_track_result(
    List<CueTrackResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_freq_point(
    List<FreqPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_smb_dir_entry(
    List<SmbDirEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_smb_share_info(
    List<SmbShareInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_result(
    MetadataResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_head_metadata_dto(
    HeadMetadataDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_room_correction_result(
    RoomCorrectionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_smb_dir_entry(SmbDirEntry self, SseSerializer serializer);

  @protected
  void sse_encode_smb_share_info(SmbShareInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
