// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audio_output_fill_buffer_stereo`, `clear_ringbuf`, `run_decoder`

Future<void> initAudioRingbuf() =>
    RustLib.instance.api.crateApiAudioOutputInitAudioRingbuf();

Future<void> startFileDecoder({required String path, double? seekSecs}) =>
    RustLib.instance.api.crateApiAudioOutputStartFileDecoder(
      path: path,
      seekSecs: seekSecs,
    );

Future<void> stopFileDecoder() =>
    RustLib.instance.api.crateApiAudioOutputStopFileDecoder();
