// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 解码音频文件到 PCM f32 交错样本（一次性解完整个文件）
Future<DecodeResult> decodeFile({required String path}) =>
    RustLib.instance.api.crateApiDecodeDecodeFile(path: path);

/// 解码 DSD 文件到 PCM f32
Future<DecodeResult> decodeDsdFile({required String path}) =>
    RustLib.instance.api.crateApiDecodeDecodeDsdFile(path: path);

/// 检查文件是否是 DSD 格式
Future<bool> isDsdFile({required String path}) =>
    RustLib.instance.api.crateApiDecodeIsDsdFile(path: path);

/// 创建流式解码器，立刻启动后台解码线程
/// 可选 seek_secs：从指定秒数开始解码
Future<StreamDecoder> streamDecoderCreate({
  required String path,
  double? seekSecs,
}) => RustLib.instance.api.crateApiDecodeStreamDecoderCreate(
  path: path,
  seekSecs: seekSecs,
);

/// 获取下一块解码数据（等待最多 300ms 或累积到 ~12288 帧，减少 FFI 调用频率）
Future<DecodeChunk?> streamDecoderNextChunk({required StreamDecoder decoder}) =>
    RustLib.instance.api.crateApiDecodeStreamDecoderNextChunk(decoder: decoder);

/// 停止流式解码
Future<void> streamDecoderStop({required StreamDecoder decoder}) =>
    RustLib.instance.api.crateApiDecodeStreamDecoderStop(decoder: decoder);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StreamDecoder>>
abstract class StreamDecoder implements RustOpaqueInterface {}

/// 流式解码的 PCM 数据块
class DecodeChunk {
  final Float32List samples;
  final int sampleRate;
  final int channels;

  const DecodeChunk({
    required this.samples,
    required this.sampleRate,
    required this.channels,
  });

  @override
  int get hashCode =>
      samples.hashCode ^ sampleRate.hashCode ^ channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodeChunk &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          sampleRate == other.sampleRate &&
          channels == other.channels;
}

/// 解码结果
class DecodeResult {
  final Float32List samples;
  final int sampleRate;
  final int channels;
  final double durationSecs;

  const DecodeResult({
    required this.samples,
    required this.sampleRate,
    required this.channels,
    required this.durationSecs,
  });

  @override
  int get hashCode =>
      samples.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodeResult &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          durationSecs == other.durationSecs;
}
