// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_engine`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `engine_read_samples`

/// 初始化引擎，使用 HW_SAMPLE_RATE（由 Swift 设 set_hw_sample_rate 传入）
Future<void> engineInit() => RustLib.instance.api.crateApiEngineEngineInit();

/// 完整参数初始化引擎
Future<void> engineInitEx({
  required int sr,
  required int channels,
  required int bufferMs,
  required int crossfadeMs,
  required bool bitPerfect,
  required bool autoSampleRate,
  required bool exclusiveMode,
  String? outputDevice,
}) => RustLib.instance.api.crateApiEngineEngineInitEx(
  sr: sr,
  channels: channels,
  bufferMs: bufferMs,
  crossfadeMs: crossfadeMs,
  bitPerfect: bitPerfect,
  autoSampleRate: autoSampleRate,
  exclusiveMode: exclusiveMode,
  outputDevice: outputDevice,
);

Future<void> engineDeinit() =>
    RustLib.instance.api.crateApiEngineEngineDeinit();

Future<String?> enginePollEvents() =>
    RustLib.instance.api.crateApiEngineEnginePollEvents();

/// 检查是否有新的事件发生并返回事件类型
Future<String?> engineTakeEvent() =>
    RustLib.instance.api.crateApiEngineEngineTakeEvent();

Future<void> enginePlay({required String path}) =>
    RustLib.instance.api.crateApiEngineEnginePlay(path: path);

Future<void> enginePlayQueue({required List<String> paths}) =>
    RustLib.instance.api.crateApiEngineEnginePlayQueue(paths: paths);

Future<void> enginePause() => RustLib.instance.api.crateApiEngineEnginePause();

Future<void> engineResume() =>
    RustLib.instance.api.crateApiEngineEngineResume();

Future<void> engineStop() => RustLib.instance.api.crateApiEngineEngineStop();

Future<void> engineSeek({required double posSecs}) =>
    RustLib.instance.api.crateApiEngineEngineSeek(posSecs: posSecs);

Future<void> engineNext() => RustLib.instance.api.crateApiEngineEngineNext();

Future<void> enginePrev() => RustLib.instance.api.crateApiEngineEnginePrev();

Future<void> engineSetPeqBand({
  required int index,
  required double freq,
  required double gainDb,
  required double q,
}) => RustLib.instance.api.crateApiEngineEngineSetPeqBand(
  index: index,
  freq: freq,
  gainDb: gainDb,
  q: q,
);

Future<void> engineApplyPreset({required String presetName}) => RustLib
    .instance
    .api
    .crateApiEngineEngineApplyPreset(presetName: presetName);

Future<void> engineSetVolume({required double vol}) =>
    RustLib.instance.api.crateApiEngineEngineSetVolume(vol: vol);

Future<void> engineSetStereoWidener({
  required bool enabled,
  required double width,
}) => RustLib.instance.api.crateApiEngineEngineSetStereoWidener(
  enabled: enabled,
  width: width,
);

Future<void> engineSetSpeed({required double speed}) =>
    RustLib.instance.api.crateApiEngineEngineSetSpeed(speed: speed);

/// 设置引擎输出采样率（下次播放生效）。
///
/// iOS bit-perfect 协调：Swift 先把 `AVAudioSession` 设到目标速率并读回实际速率，
/// Dart 再调用本方法使引擎输出速率与设备一致。命令走 FIFO 通道，
/// 在同一首播放之前发送即可保证先于 play 生效。若速率 == 文件速率则不重采样（bit-perfect）。
Future<void> engineSetOutputSampleRate({required int rate}) =>
    RustLib.instance.api.crateApiEngineEngineSetOutputSampleRate(rate: rate);

Future<void> engineSetCrossfeed({required bool enabled}) =>
    RustLib.instance.api.crateApiEngineEngineSetCrossfeed(enabled: enabled);

Future<void> engineSetPlayMode({required int mode}) =>
    RustLib.instance.api.crateApiEngineEngineSetPlayMode(mode: mode);

Future<void> engineLoadIr({required String path}) =>
    RustLib.instance.api.crateApiEngineEngineLoadIr(path: path);

Future<void> engineClearIr() =>
    RustLib.instance.api.crateApiEngineEngineClearIr();

Future<void> engineSetReplaygainGain({required double gainDb}) =>
    RustLib.instance.api.crateApiEngineEngineSetReplaygainGain(gainDb: gainDb);

Future<double> enginePositionSecs() =>
    RustLib.instance.api.crateApiEngineEnginePositionSecs();

Future<double> engineDurationSecs() =>
    RustLib.instance.api.crateApiEngineEngineDurationSecs();

Future<bool> engineIsPlaying() =>
    RustLib.instance.api.crateApiEngineEngineIsPlaying();

Future<String> engineCurrentPath() =>
    RustLib.instance.api.crateApiEngineEngineCurrentPath();

Future<String> engineLastError() =>
    RustLib.instance.api.crateApiEngineEngineLastError();

Future<LevelsDto> engineLevels() =>
    RustLib.instance.api.crateApiEngineEngineLevels();

Future<BigInt> engineUnderrunCount() =>
    RustLib.instance.api.crateApiEngineEngineUnderrunCount();

Future<int> engineQueueLen() =>
    RustLib.instance.api.crateApiEngineEngineQueueLen();

Future<String> engineQueuePathAt({required int index}) =>
    RustLib.instance.api.crateApiEngineEngineQueuePathAt(index: index);

Future<void> engineRemoveFromQueue({required int index}) =>
    RustLib.instance.api.crateApiEngineEngineRemoveFromQueue(index: index);

class LevelsDto {
  final double rms;
  final double peak;
  final bool clip;

  const LevelsDto({required this.rms, required this.peak, required this.clip});

  static Future<LevelsDto> default_() =>
      RustLib.instance.api.crateApiEngineLevelsDtoDefault();

  @override
  int get hashCode => rms.hashCode ^ peak.hashCode ^ clip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LevelsDto &&
          runtimeType == other.runtimeType &&
          rms == other.rms &&
          peak == other.peak &&
          clip == other.clip;
}
