// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_cover_lofty`

/// 读取音频文件封面图（JPEG/PNG 原始字节），用 lofty 提取
Future<Uint8List> getCoverBytes({required String path}) =>
    RustLib.instance.api.crateApiMetadataGetCoverBytes(path: path);

/// 读取音频文件元数据（标题/艺术家/专辑/封面/时长）
Future<MetadataResult> readMetadata({required String path}) =>
    RustLib.instance.api.crateApiMetadataReadMetadata(path: path);

/// 音频文件元数据
class MetadataResult {
  final String? title;
  final String? artist;
  final String? album;
  final double durationSecs;
  final bool hasCover;

  const MetadataResult({
    this.title,
    this.artist,
    this.album,
    required this.durationSecs,
    required this.hasCover,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationSecs.hashCode ^
      hasCover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetadataResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationSecs == other.durationSecs &&
          hasCover == other.hasCover;
}
