// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 解析播放列表文件（自动识别 M3U/M3U8/PLS），返回条目列表
Future<List<PlaylistEntryResult>> parsePlaylistFile({required String path}) =>
    RustLib.instance.api.crateApiPlaylistParsePlaylistFile(path: path);

/// 播放列表条目
class PlaylistEntryResult {
  final String path;
  final String? title;
  final double durationSecs;

  const PlaylistEntryResult({
    required this.path,
    this.title,
    required this.durationSecs,
  });

  @override
  int get hashCode => path.hashCode ^ title.hashCode ^ durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistEntryResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          durationSecs == other.durationSecs;
}
