// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/analyze.dart';
import 'api/audio_output.dart';
import 'api/cue.dart';
import 'api/decode.dart';
import 'api/device.dart';
import 'api/dsp.dart';
import 'api/engine.dart';
import 'api/metadata.dart';
import 'api/playlist.dart';
import 'api/smb.dart';
import 'api/webdav.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_StreamDecoderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoderPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  StreamDecoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    dynamic raw,
  );

  @protected
  StreamDecoder
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    dynamic raw,
  );

  @protected
  StreamDecoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    dynamic raw,
  );

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnalyzeResult dco_decode_analyze_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DecodeChunk dco_decode_box_autoadd_decode_chunk(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  OutputDecisionDto dco_decode_box_autoadd_output_decision_dto(dynamic raw);

  @protected
  CueFileResult dco_decode_cue_file_result(dynamic raw);

  @protected
  CueSheetResult dco_decode_cue_sheet_result(dynamic raw);

  @protected
  CueTrackResult dco_decode_cue_track_result(dynamic raw);

  @protected
  DecodeChunk dco_decode_decode_chunk(dynamic raw);

  @protected
  DecodeResult dco_decode_decode_result(dynamic raw);

  @protected
  DeviceInfoDto dco_decode_device_info_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  LevelsDto dco_decode_levels_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CueFileResult> dco_decode_list_cue_file_result(dynamic raw);

  @protected
  List<CueTrackResult> dco_decode_list_cue_track_result(dynamic raw);

  @protected
  List<DeviceInfoDto> dco_decode_list_device_info_dto(dynamic raw);

  @protected
  List<PlaylistEntryResult> dco_decode_list_playlist_entry_result(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SmbDirEntry> dco_decode_list_smb_dir_entry(dynamic raw);

  @protected
  List<SmbShareInfo> dco_decode_list_smb_share_info(dynamic raw);

  @protected
  MetadataResult dco_decode_metadata_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DecodeChunk? dco_decode_opt_box_autoadd_decode_chunk(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  OutputDecisionDto? dco_decode_opt_box_autoadd_output_decision_dto(
    dynamic raw,
  );

  @protected
  OutputDecisionDto dco_decode_output_decision_dto(dynamic raw);

  @protected
  PlaylistEntryResult dco_decode_playlist_entry_result(dynamic raw);

  @protected
  ReplayGainResult dco_decode_replay_gain_result(dynamic raw);

  @protected
  SmbDirEntry dco_decode_smb_dir_entry(dynamic raw);

  @protected
  SmbShareInfo dco_decode_smb_share_info(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  StreamDecoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    SseDeserializer deserializer,
  );

  @protected
  StreamDecoder
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    SseDeserializer deserializer,
  );

  @protected
  StreamDecoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnalyzeResult sse_decode_analyze_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DecodeChunk sse_decode_box_autoadd_decode_chunk(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  OutputDecisionDto sse_decode_box_autoadd_output_decision_dto(
    SseDeserializer deserializer,
  );

  @protected
  CueFileResult sse_decode_cue_file_result(SseDeserializer deserializer);

  @protected
  CueSheetResult sse_decode_cue_sheet_result(SseDeserializer deserializer);

  @protected
  CueTrackResult sse_decode_cue_track_result(SseDeserializer deserializer);

  @protected
  DecodeChunk sse_decode_decode_chunk(SseDeserializer deserializer);

  @protected
  DecodeResult sse_decode_decode_result(SseDeserializer deserializer);

  @protected
  DeviceInfoDto sse_decode_device_info_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  LevelsDto sse_decode_levels_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CueFileResult> sse_decode_list_cue_file_result(
    SseDeserializer deserializer,
  );

  @protected
  List<CueTrackResult> sse_decode_list_cue_track_result(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceInfoDto> sse_decode_list_device_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistEntryResult> sse_decode_list_playlist_entry_result(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SmbDirEntry> sse_decode_list_smb_dir_entry(SseDeserializer deserializer);

  @protected
  List<SmbShareInfo> sse_decode_list_smb_share_info(
    SseDeserializer deserializer,
  );

  @protected
  MetadataResult sse_decode_metadata_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DecodeChunk? sse_decode_opt_box_autoadd_decode_chunk(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  OutputDecisionDto? sse_decode_opt_box_autoadd_output_decision_dto(
    SseDeserializer deserializer,
  );

  @protected
  OutputDecisionDto sse_decode_output_decision_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlaylistEntryResult sse_decode_playlist_entry_result(
    SseDeserializer deserializer,
  );

  @protected
  ReplayGainResult sse_decode_replay_gain_result(SseDeserializer deserializer);

  @protected
  SmbDirEntry sse_decode_smb_dir_entry(SseDeserializer deserializer);

  @protected
  SmbShareInfo sse_decode_smb_share_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    StreamDecoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    StreamDecoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    StreamDecoder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_analyze_result(AnalyzeResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_decode_chunk(
    DecodeChunk self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_output_decision_dto(
    OutputDecisionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cue_file_result(CueFileResult self, SseSerializer serializer);

  @protected
  void sse_encode_cue_sheet_result(
    CueSheetResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cue_track_result(
    CueTrackResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decode_chunk(DecodeChunk self, SseSerializer serializer);

  @protected
  void sse_encode_decode_result(DecodeResult self, SseSerializer serializer);

  @protected
  void sse_encode_device_info_dto(DeviceInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_levels_dto(LevelsDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cue_file_result(
    List<CueFileResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_cue_track_result(
    List<CueTrackResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_info_dto(
    List<DeviceInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_entry_result(
    List<PlaylistEntryResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_smb_dir_entry(
    List<SmbDirEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_smb_share_info(
    List<SmbShareInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_metadata_result(
    MetadataResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_decode_chunk(
    DecodeChunk? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_output_decision_dto(
    OutputDecisionDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_decision_dto(
    OutputDecisionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playlist_entry_result(
    PlaylistEntryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_replay_gain_result(
    ReplayGainResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_smb_dir_entry(SmbDirEntry self, SseSerializer serializer);

  @protected
  void sse_encode_smb_share_info(SmbShareInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_wavelink_mobile_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_wavelink_mobile_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoder =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStreamDecoderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
