// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 分析音频文件（BPM + 调性 + 能量）
Future<AnalyzeResult> analyzeFile({required String path}) =>
    RustLib.instance.api.crateApiAnalyzeAnalyzeFile(path: path);

/// 分析 PCM 样本数据
Future<AnalyzeResult> analyzePcmSamples({
  required List<double> samples,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiAnalyzeAnalyzePcmSamples(
  samples: samples,
  sampleRate: sampleRate,
  channels: channels,
);

/// 音频分析结果
class AnalyzeResult {
  final double? bpm;
  final String? key;
  final double? energy;

  const AnalyzeResult({this.bpm, this.key, this.energy});

  @override
  int get hashCode => bpm.hashCode ^ key.hashCode ^ energy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalyzeResult &&
          runtimeType == other.runtimeType &&
          bpm == other.bpm &&
          key == other.key &&
          energy == other.energy;
}
